<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_PersonalInfo_Container</name>
   <tag></tag>
   <elementGuidId>72729f8e-9ab6-4c1c-ab31-0e3c3177fe35</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__PWS_ROOT__']/div/div/div[3]/div/div/div/div[2]/div/div[2]/div[2]/div[4]/div[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>[data-test-id=&quot;personalInformationContainer&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>b7c1fee4-f02a-431c-a46c-821885594ed8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-test-id</name>
      <type>Main</type>
      <value>personalInformationContainer</value>
      <webElementGuid>29b85858-b357-4f04-bf39-1f1fe149ee61</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ADXRXN</value>
      <webElementGuid>696a272e-ab88-4fad-be0a-df593e495286</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Personal informationBirthdateGenderGenderMaleFemaleNon-binaryCountry/RegionLanguageAfrikaansBahasa IndonesiaBahasa MalaysiaČeštinaDanskDeutschEnglish (Australia)English (India)English (UK)English (US)Español (Américas)Español (Argentina)Español (España)Español (México)FrançaisHrvatskiItalianoMagyarNederlandsNorsk bokmålPolskiPortuguês (Brasil)Português (Europeu)RomânăSlovenčinaSuomiSvenskaTagalogTiếng ViệtTürkçeΕλληνικάБългарскиРусскийУкраїнськаעבריתالعربيةहिन्दीবাংলাతెలుగుภาษาไทย한국어日本語简体中文繁體中文</value>
      <webElementGuid>f6beb2db-f606-44ce-b11f-4fad4a03f3a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__PWS_ROOT__&quot;)/div[@class=&quot;ADXRXN&quot;]/div[@class=&quot;ADXRXN&quot;]/div[@class=&quot;appContent&quot;]/div[@class=&quot;ADXRXN&quot;]/div[@class=&quot;mainContainer&quot;]/div[@class=&quot;ADXRXN C48Khy KDGhSV Tjcf3c zEVE_X&quot;]/div[@class=&quot;ADXRXN c49R7p g0I6wi zDq_D0 PSnbKb&quot;]/div[@class=&quot;ADXRXN C48Khy _tKaHB eeaciM gbTsx5 xLeAAe zEVE_X&quot;]/div[@class=&quot;ADXRXN AywgSp C48Khy IUaGft PaBcSf ixXyxx c49R7p g0I6wi coNeet gSktR2 i1hWBD&quot;]/div[@class=&quot;ADXRXN Emc7hI _tKaHB zEVE_X&quot;]/div[@class=&quot;ADXRXN To17G1&quot;]/div[@class=&quot;ADXRXN&quot;]</value>
      <webElementGuid>81fa621c-8ed7-4742-941d-3218ae590959</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__PWS_ROOT__']/div/div/div[3]/div/div/div/div[2]/div/div[2]/div[2]/div[4]/div[2]</value>
      <webElementGuid>32a54e6f-815e-40d7-846f-887125baa4e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Convert account'])[1]/following::div[1]</value>
      <webElementGuid>d8c37931-c434-4b95-bfb9-f0dce7ec5889</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Convert to a business account'])[1]/following::div[5]</value>
      <webElementGuid>0d184c66-0fc5-49e0-8770-0e06cfd19e1b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div[2]</value>
      <webElementGuid>d81436ec-ec8c-4017-9a83-43660a3370c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Personal informationBirthdateGenderGenderMaleFemaleNon-binaryCountry/RegionLanguageAfrikaansBahasa IndonesiaBahasa MalaysiaČeštinaDanskDeutschEnglish (Australia)English (India)English (UK)English (US)Español (Américas)Español (Argentina)Español (España)Español (México)FrançaisHrvatskiItalianoMagyarNederlandsNorsk bokmålPolskiPortuguês (Brasil)Português (Europeu)RomânăSlovenčinaSuomiSvenskaTagalogTiếng ViệtTürkçeΕλληνικάБългарскиРусскийУкраїнськаעבריתالعربيةहिन्दीবাংলাతెలుగుภาษาไทย한국어日本語简体中文繁體中文' or . = 'Personal informationBirthdateGenderGenderMaleFemaleNon-binaryCountry/RegionLanguageAfrikaansBahasa IndonesiaBahasa MalaysiaČeštinaDanskDeutschEnglish (Australia)English (India)English (UK)English (US)Español (Américas)Español (Argentina)Español (España)Español (México)FrançaisHrvatskiItalianoMagyarNederlandsNorsk bokmålPolskiPortuguês (Brasil)Português (Europeu)RomânăSlovenčinaSuomiSvenskaTagalogTiếng ViệtTürkçeΕλληνικάБългарскиРусскийУкраїнськаעבריתالعربيةहिन्दीবাংলাతెలుగుภาษาไทย한국어日本語简体中文繁體中文')]</value>
      <webElementGuid>2bae3749-dfcd-44d9-b6e8-38394c5ba0d7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
