<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_ConnectedDevices</name>
   <tag></tag>
   <elementGuidId>d1a1b20a-b804-4d98-b3e8-809c9343f0b1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.H2DtUH.KwViV7.FE_3R1.KDGhSV._tKaHB.qtP9fl > div.ADXRXN.i1hWBD</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@data-sess-id]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>.H2DtUH > div:nth-child(9)</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>e8e13a7a-3106-44d8-a985-b5ec698e48f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ADXRXN i1hWBD</value>
      <webElementGuid>53709ac7-858e-40e4-b94c-fc9ca15f692c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Last accessed:January 19, 2026, 8:03 PMLocation:Hanoi, Vietnam (Approximate, based on IP = 14.191.34.186)Device type:Edge on Windows 10End ActivityLast accessed:January 19, 2026, 8:06 PMLocation:Hanoi, Vietnam (Approximate, based on IP = 14.191.34.186)Device type:Edge on Windows 10Current SessionLast accessed:January 19, 2026, 7:48 PMLocation:Hanoi, Vietnam (Approximate, based on IP = 14.191.34.186)Device type:Edge on Windows 10End ActivityLast accessed:January 19, 2026, 8:03 PMLocation:Hanoi, Vietnam (Approximate, based on IP = 14.191.34.186)Device type:Edge on Windows 10End ActivityLast accessed:January 19, 2026, 4:22 PMLocation:Hanoi, Vietnam (Approximate, based on IP = 14.191.34.186)Device type:Edge on Windows 10End ActivityLast accessed:January 19, 2026, 4:22 PMLocation:Hanoi, Vietnam (Approximate, based on IP = 14.191.34.186)Device type:Edge on Windows 10End ActivityLast accessed:January 15, 2026, 5:21 PMLocation:Hanoi, Vietnam (Approximate, based on IP = 118.69.178.190)Device type:Edge on Windows 10End ActivityLast accessed:January 15, 2026, 5:01 PMLocation:Hanoi, Vietnam (Approximate, based on IP = 118.69.178.190)Device type:Edge on Windows 10End ActivityLast accessed:January 15, 2026, 4:51 PMLocation:Hanoi, Vietnam (Approximate, based on IP = 118.69.178.190)Device type:Edge on Windows 10End ActivityLast accessed:January 15, 2026, 3:59 PMLocation:Hanoi, Vietnam (Approximate, based on IP = 118.69.178.190)Device type:Edge on Windows 10End ActivityLast accessed:January 15, 2026, 5:10 PMLocation:Hanoi, Vietnam (Approximate, based on IP = 118.69.178.190)Device type:Edge on Windows 10End ActivityLast accessed:January 15, 2026, 3:13 PMLocation:Hanoi, Vietnam (Approximate, based on IP = 123.16.85.75)Device type:Edge on Windows 10End ActivityLast accessed:January 15, 2026, 3:09 PMLocation:nullDevice type: End Activity</value>
      <webElementGuid>d791546a-cc7b-4bfe-92ef-3cd9a671765e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__PWS_ROOT__&quot;)/div[@class=&quot;ADXRXN&quot;]/div[@class=&quot;ADXRXN&quot;]/div[@class=&quot;appContent&quot;]/div[@class=&quot;ADXRXN&quot;]/div[@class=&quot;mainContainer&quot;]/div[@class=&quot;ADXRXN C48Khy KDGhSV Tjcf3c zEVE_X&quot;]/div[@class=&quot;ADXRXN c49R7p g0I6wi zDq_D0 PSnbKb&quot;]/div[@class=&quot;ADXRXN C48Khy _tKaHB eeaciM gbTsx5 xLeAAe zEVE_X&quot;]/div[@class=&quot;ADXRXN AywgSp C48Khy IUaGft PaBcSf ixXyxx c49R7p g0I6wi coNeet gSktR2 i1hWBD&quot;]/div[@class=&quot;H2DtUH KwViV7 FE_3R1 KDGhSV _tKaHB qtP9fl&quot;]/div[@class=&quot;ADXRXN i1hWBD&quot;]</value>
      <webElementGuid>c23c3b03-db89-4009-9c7c-92ba3244e090</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value></value>
      <webElementGuid>76e34eeb-2577-4632-b749-4051dabbeac6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value></value>
      <webElementGuid>1ef99fee-f163-4baa-a81b-1eb1b846f83d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value></value>
      <webElementGuid>706b66d1-3047-463c-8e02-5773db41819d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value></value>
      <webElementGuid>42fd7da7-07a3-446b-b70e-0dcc7c56689a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value></value>
      <webElementGuid>f6c82879-c69e-4445-8600-cc9a2530f91b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
