<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Reset</name>
   <tag></tag>
   <elementGuidId>f4018084-0c42-4902-945a-9a79a649817c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.WuRgKB.eMU5i5.o5UlW_.h3gMqR.cZLkj_</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='search_filters_drawer']/div/div[3]/div/div/div/button/div/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>[data-test-id=&quot;filter-clear-button&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>80f72d04-6b36-4549-ae5b-2c897b1fda44</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>WuRgKB eMU5i5 o5UlW_ h3gMqR cZLkj_</value>
      <webElementGuid>f1e15171-f52b-421d-88ea-9a14147e9b4b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Reset</value>
      <webElementGuid>c1066dd2-b0ec-4264-b082-a346be3aab80</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;search_filters_drawer&quot;)/div[@class=&quot;ADXRXN&quot;]/div[@class=&quot;ADXRXN NYgy1O TfR6nu k5oQr4&quot;]/div[@class=&quot;ADXRXN ecEhnF kF2VEF zEVE_X&quot;]/div[@class=&quot;ADXRXN C48Khy Tjcf3c zEVE_X&quot;]/div[@class=&quot;ADXRXN BGUL9_&quot;]/button[@class=&quot;G0yGFD ap8aAM Q3hcOU j0pMjI E6J5D_ GaMK1V O0u6sV&quot;]/div[@class=&quot;oxThCB&quot;]/div[@class=&quot;WuRgKB eMU5i5 o5UlW_ h3gMqR cZLkj_&quot;]</value>
      <webElementGuid>592ff2b4-523a-4e32-9dce-c5ba33c99f05</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='search_filters_drawer']/div/div[3]/div/div/div/button/div/div</value>
      <webElementGuid>db5473c3-ee56-4aa7-abc7-2c6939cea5a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Profiles'])[1]/following::div[11]</value>
      <webElementGuid>eadc499f-05dc-4cd0-86ea-2ad863ecae27</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Boards'])[1]/following::div[22]</value>
      <webElementGuid>081bb095-046a-47cf-b833-b07a7f6b66e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Apply'])[1]/preceding::div[1]</value>
      <webElementGuid>436e888d-fbe1-44d5-ab69-097cd6998709</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='MEOW HANDMADE'])[1]/preceding::div[12]</value>
      <webElementGuid>25dc6e9f-6eaa-4f8a-be27-2bc6935ff666</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Reset']/parent::*</value>
      <webElementGuid>1f6a2187-702c-4e94-8ce4-847fce39df99</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/button/div/div</value>
      <webElementGuid>83c6801a-2a26-43a3-86df-228803e3b200</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Reset' or . = 'Reset')]</value>
      <webElementGuid>26d63108-813a-4acd-893d-7db7668c6f2c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
