<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Apply</name>
   <tag></tag>
   <elementGuidId>6dfbcf8d-f449-472d-bb1b-c94a876a287f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.lIkAnG.eMU5i5.o5UlW_.h3gMqR.cZLkj_</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='search_filters_drawer']/div/div[3]/div/div/div[2]/button/div/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>[data-test-id=&quot;filter-confirm-button&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>fc0bd485-9a23-4d66-9d9e-dc741ad2236d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>lIkAnG eMU5i5 o5UlW_ h3gMqR cZLkj_</value>
      <webElementGuid>bda1779c-9ef5-41bf-99f4-6ba5f8ce777a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Apply</value>
      <webElementGuid>5a980ae1-bafb-4d53-8165-39e85a356f66</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;search_filters_drawer&quot;)/div[@class=&quot;ADXRXN&quot;]/div[@class=&quot;ADXRXN NYgy1O TfR6nu k5oQr4&quot;]/div[@class=&quot;ADXRXN ecEhnF kF2VEF zEVE_X&quot;]/div[@class=&quot;ADXRXN C48Khy Tjcf3c zEVE_X&quot;]/div[@class=&quot;ADXRXN RI9PTN&quot;]/button[@class=&quot;G0yGFD ap8aAM Q3hcOU gwpqhu E6J5D_ GaMK1V O0u6sV&quot;]/div[@class=&quot;oxThCB&quot;]/div[@class=&quot;lIkAnG eMU5i5 o5UlW_ h3gMqR cZLkj_&quot;]</value>
      <webElementGuid>54165ca8-5302-468b-84a8-3c547b4a8db6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='search_filters_drawer']/div/div[3]/div/div/div[2]/button/div/div</value>
      <webElementGuid>39625ad5-76c0-470c-873d-2553bf578fb7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Reset'])[1]/following::div[3]</value>
      <webElementGuid>d566996c-fef2-4baa-9d21-5c35969530ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Profiles'])[1]/following::div[14]</value>
      <webElementGuid>6c6da086-2eff-4b10-8e41-f9556d4467b4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Showing more search results for meow'])[1]/preceding::div[2]</value>
      <webElementGuid>dd8d5976-c895-4faa-b128-ba2fc6eb9ea1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Apply']/parent::*</value>
      <webElementGuid>dc276e77-ccd8-4ae2-8e0f-a3ba0b54e42c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/button/div/div</value>
      <webElementGuid>d55d30b7-ca70-4010-826b-4ff45fe54ea9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Apply' or . = 'Apply')]</value>
      <webElementGuid>1712aedd-01bc-4fbf-9891-6d23fe2ddbb1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
