<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Profiles_Profiles</name>
   <tag></tag>
   <elementGuidId>16f8665b-b2d0-408f-943b-ff1ca3ccb4aa</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#Profiles</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='Profiles']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#Profiles</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>11157969-0d5e-40ce-9320-d92fa99ce2d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>IsH5xf y_r4q0</value>
      <webElementGuid>acd8eaec-cf96-4052-8d27-7f962dc8db08</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Profiles</value>
      <webElementGuid>e89529df-5f87-4e48-91de-adfbdf8a8024</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>3e59e6e4-baa5-4570-826e-16534b262475</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Profiles</value>
      <webElementGuid>82b9c9da-f1d3-47c0-b479-6b206500d11c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Profiles&quot;)</value>
      <webElementGuid>e8d215d8-379a-4579-a895-90e4f1848fbc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='Profiles']</value>
      <webElementGuid>15cdd266-8d15-4c16-a1a2-c66b4f52fbaa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='search_filters_drawer']/div/div[2]/div/div/fieldset/div/div/div/div/div/div[4]/div/div/div/div[2]/div/input</value>
      <webElementGuid>6b9c4679-96e5-4bb3-867f-a698992490e3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/div/div[2]/div/input</value>
      <webElementGuid>6e9d22a4-2a12-4a4d-8012-9b9cd0bde139</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'Profiles' and @type = 'radio']</value>
      <webElementGuid>41c9e9a3-0ddb-4965-acd6-e58fb4a12135</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
