<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Videos_Videos</name>
   <tag></tag>
   <elementGuidId>d1774d1e-4df8-4e40-bd62-0b7a92afe5f7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#Videos</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='Videos']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#Videos</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>3573091d-7913-4e42-b58a-843ed26264cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>IsH5xf y_r4q0</value>
      <webElementGuid>5b69cbd4-4cbe-4837-8b09-f78f5a7c86d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Videos</value>
      <webElementGuid>1eb5f37e-a35e-48f5-84e5-07b16cf5218d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>699ed6ac-1a3d-490d-9b60-19e3b0911b47</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Videos</value>
      <webElementGuid>0b6907a6-a164-4734-8e72-e804174b1e9c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Videos&quot;)</value>
      <webElementGuid>39de8ea2-2bf6-450a-9389-e17bc2054f06</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='Videos']</value>
      <webElementGuid>fbe63b16-2175-4653-8912-cd0c26c41c8d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='search_filters_drawer']/div/div[2]/div/div/fieldset/div/div/div/div/div/div[2]/div/div/div/div[2]/div/input</value>
      <webElementGuid>6817c9e4-e7d0-4e85-8c23-440f64cdd966</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div[2]/div/input</value>
      <webElementGuid>5cae24d8-7748-4fc1-94b4-02db85fe9c7a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'Videos' and @type = 'radio']</value>
      <webElementGuid>765a6d7b-f472-4514-85f9-7806c2199a66</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
