<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Boards_Boards</name>
   <tag></tag>
   <elementGuidId>83288be5-69ac-48e6-8ad7-03f17973a215</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#Boards</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='Boards']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#Boards</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ba8ff996-e6ae-4a96-9b52-86b5cdb44874</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>IsH5xf y_r4q0</value>
      <webElementGuid>7597c1d4-bb91-4909-92ef-e6097429dce6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Boards</value>
      <webElementGuid>584b076d-58d9-4abe-8b1c-89ba83998ef8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>f1965d4e-d545-4a62-8a6d-8be5e37e8d70</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Boards</value>
      <webElementGuid>7666cf82-db31-4ea7-9de6-343f22c72861</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Boards&quot;)</value>
      <webElementGuid>0310bd3c-f3a5-4c68-84bc-740666403407</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='Boards']</value>
      <webElementGuid>438f2273-0ce1-48a4-abd0-021aae615c52</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='search_filters_drawer']/div/div[2]/div/div/fieldset/div/div/div/div/div/div[3]/div/div/div/div[2]/div/input</value>
      <webElementGuid>ebc9bde2-c15f-4011-b7fe-2f7be5e9dbb8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/div[2]/div/input</value>
      <webElementGuid>c25c5a95-a27a-44f8-b331-70a645a9d9fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'Boards' and @type = 'radio']</value>
      <webElementGuid>a8154c5e-f087-4e86-96d7-a5f5f0d0e5ec</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
