<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_KwInstead</name>
   <tag></tag>
   <elementGuidId>3b8b448c-1422-4775-96f6-553de68fa127</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.etmDmh.i7jpet.DodKMr.hlFz_k.Q3hcOU.AMxolZ.zlD4hU.eTLu1g.O0u6sV</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@href='/search/pins/?q=natre&amp;rs=typo_auto_original&amp;auto_correction_disabled=true']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;natra&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>9758088c-7bd2-436e-b0ea-50b02153f8ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>etmDmh i7jpet DodKMr hlFz_k Q3hcOU AMxolZ zlD4hU eTLu1g O0u6sV</value>
      <webElementGuid>3af74f9e-4acd-4398-b8f0-49b0dbf4b5f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/search/pins/?q=natra&amp;rs=typo_auto_original&amp;auto_correction_disabled=true</value>
      <webElementGuid>c37e0a4e-68c8-4153-9c9c-ed3b58b8658c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>natra</value>
      <webElementGuid>f282edee-df92-4000-af88-a71901a45168</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__PWS_ROOT__&quot;)/div[@class=&quot;ADXRXN&quot;]/div[@class=&quot;ADXRXN&quot;]/div[@class=&quot;appContent&quot;]/div[@class=&quot;ADXRXN&quot;]/div[@class=&quot;mainContainer&quot;]/div[@class=&quot;KvKvqR&quot;]/div[1]/div[@class=&quot;ADXRXN AsRsEE _xSIdT ecEhnF&quot;]/div[@class=&quot;ADXRXN&quot;]/div[@class=&quot;WuRgKB aMgNKE YfEt3H v_eFe4 qnEc35 hxKTA7 mm0O_j&quot;]/span[@class=&quot;WuRgKB aMgNKE YfEt3H v_eFe4 qnEc35 hxKTA7 rszMzv&quot;]/a[@class=&quot;etmDmh i7jpet DodKMr hlFz_k Q3hcOU AMxolZ zlD4hU eTLu1g O0u6sV&quot;]</value>
      <webElementGuid>4114d352-53d5-4c23-979b-0e8da5eb7130</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__PWS_ROOT__']/div/div/div[3]/div/div/div[2]/div/div/div/div/span[2]/a</value>
      <webElementGuid>b340d812-313f-4617-aab0-a14722ffdeee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value></value>
      <webElementGuid>151097ab-c975-43e9-9623-5ec2ad46d2c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value></value>
      <webElementGuid>fb70f71b-1f6b-4ed6-bbb9-338364e93ebb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value></value>
      <webElementGuid>69563c6b-dd20-4920-b3a7-acff3748ab2f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value></value>
      <webElementGuid>51be698a-2f1a-48b1-98bb-494ccb1132e6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value></value>
      <webElementGuid>66771852-93c5-4988-9fb2-297cecfe2845</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value></value>
      <webElementGuid>ad18ca0a-fdac-4225-a1f1-23620fadf940</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value></value>
      <webElementGuid>dbc28bb8-50a5-425b-80e9-7bca6ed97797</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value></value>
      <webElementGuid>7fb007aa-e971-4a17-a812-fcfe2842072a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
