<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Instead</name>
   <tag></tag>
   <elementGuidId>51161e5c-9792-422d-9b17-a9264ce558cb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.WuRgKB.aMgNKE.YfEt3H.v_eFe4.qnEc35.hxKTA7.mm0O_j</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@data-test-id='search-autocorrect']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Here's what we found for natura. Search natra instead?&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>891b5de9-bd73-4408-9244-9a68bfaa45f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>WuRgKB aMgNKE YfEt3H v_eFe4 qnEc35 hxKTA7 mm0O_j</value>
      <webElementGuid>d0e17d72-d1ed-41cf-b159-a1e27c9cae8c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Here's what we found for natura. Search natra instead?</value>
      <webElementGuid>79abba62-644f-4d9b-9124-c6ca2f4c8de5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__PWS_ROOT__&quot;)/div[@class=&quot;ADXRXN&quot;]/div[@class=&quot;ADXRXN&quot;]/div[@class=&quot;appContent&quot;]/div[@class=&quot;ADXRXN&quot;]/div[@class=&quot;mainContainer&quot;]/div[@class=&quot;KvKvqR&quot;]/div[1]/div[@class=&quot;ADXRXN AsRsEE _xSIdT ecEhnF&quot;]/div[@class=&quot;ADXRXN&quot;]/div[@class=&quot;WuRgKB aMgNKE YfEt3H v_eFe4 qnEc35 hxKTA7 mm0O_j&quot;]</value>
      <webElementGuid>f41b54c7-fe06-4a7c-afdf-a2d4cf868e03</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value></value>
      <webElementGuid>06854124-3ddc-486a-848e-9922a8aa43c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value></value>
      <webElementGuid>be2e8991-93e6-4da2-8004-cfe5ad344a0c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value></value>
      <webElementGuid>6f9c5c9a-4d65-4554-addc-217d2611c002</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value></value>
      <webElementGuid>26ed8e99-e2c3-4007-9d7f-9cb557353f2c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value></value>
      <webElementGuid>8524ea78-6cdf-46f2-8704-d98bd3aeae58</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
