<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_MoreBoard</name>
   <tag></tag>
   <elementGuidId>4c27251a-f37e-4a94-acaf-4569569b23c8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.G0yGFD.ap8aAM.Q3hcOU.iMxAxK.itmoZr.GaMK1V.O0u6sV</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@data-test-id='PinBetterSaveDropdown']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>[data-test-id=&quot;PinBetterSaveDropdown&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>3948c6d9-cf4f-4498-9a33-c3576f50dbfa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>_r_l_</value>
      <webElementGuid>9ac71d73-916d-42c8-a11d-d97ab743704b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>ac39f5e8-a242-45fb-ab85-25994f02ad20</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-haspopup</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>fcc70cef-6588-4fd9-81c5-8270c51e85d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Select a board to save to: Meow</value>
      <webElementGuid>42e6191f-a115-421b-bb8d-aa4348a61645</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>G0yGFD ap8aAM Q3hcOU iMxAxK itmoZr GaMK1V O0u6sV</value>
      <webElementGuid>2bcc5bb8-254b-4326-ad1a-7456428fab24</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-test-id</name>
      <type>Main</type>
      <value>PinBetterSaveDropdown</value>
      <webElementGuid>c7f87a39-1ff2-473a-b4a7-83264308e4da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>70af524a-9a31-4a5b-8597-035196850c7a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>6f505081-3056-4019-a7a1-1d9655aed098</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Meow</value>
      <webElementGuid>5e73167b-e3d9-4045-ae43-e78b29e2b377</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;gradient&quot;)/div[@class=&quot;ADXRXN&quot;]/div[@class=&quot;ADXRXN _tKaHB ecEhnF zEVE_X&quot;]/div[@class=&quot;ADXRXN wl0pCr&quot;]/div[@class=&quot;ADXRXN XC5OnJ gEQpi5&quot;]/div[@class=&quot;ADXRXN&quot;]/div[@class=&quot;ADXRXN gEQpi5&quot;]/div[@class=&quot;ADXRXN BVzdUh ecEhnF gEQpi5 zEVE_X&quot;]/div[@class=&quot;ADXRXN&quot;]/div[@class=&quot;H2DtUH KwViV7 FE_3R1 KDGhSV Tjcf3c qtP9fl&quot;]/div[@class=&quot;H2DtUH KwViV7 FE_3R1 _tKaHB wl0pCr&quot;]/div[@class=&quot;ADXRXN AzXCPS KDGhSV ZEBTif _tKaHB qtP9fl zEVE_X&quot;]/div[@class=&quot;ADXRXN BVzdUh Yh17xG dSlwuX kF2VEF sSBu24 zEVE_X&quot;]/div[@class=&quot;ADXRXN ecEhnF iHQedX&quot;]/div[@class=&quot;ADXRXN&quot;]/div[@class=&quot;H2DtUH KwViV7 FE_3R1 Tjcf3c qJUqe1 qtP9fl&quot;]/div[@class=&quot;H2DtUH c1Gamg z6WAHi Tjcf3c sSBu24&quot;]/div[@class=&quot;oRZ5_s&quot;]/div[@class=&quot;ADXRXN _HYyJc&quot;]/div[@class=&quot;ADXRXN&quot;]/div[@class=&quot;ADXRXN zEVE_X&quot;]/div[@class=&quot;ADXRXN gHrR3r sSBu24 zEVE_X&quot;]/div[@class=&quot;ADXRXN wl0pCr&quot;]/button[@class=&quot;G0yGFD ap8aAM Q3hcOU iMxAxK itmoZr GaMK1V O0u6sV&quot;]</value>
      <webElementGuid>b2fa3114-4bfc-4503-b6b2-b00ed0a86c21</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value></value>
      <webElementGuid>c3581789-f522-41fb-8900-cede0c6413b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value></value>
      <webElementGuid>02f77ce9-634c-4309-8270-e783071b5cd9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value></value>
      <webElementGuid>5d138f53-e175-4c92-b6ab-037c09039483</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value></value>
      <webElementGuid>07fd50e0-4ae1-4721-88a5-0aa7243cd978</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value></value>
      <webElementGuid>e1c47b88-7b16-496a-9b3e-6d16cd649ebb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value></value>
      <webElementGuid>d793b5fc-beab-4c79-9063-02f0cc72e9cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value></value>
      <webElementGuid>be0c8829-9f23-4ac2-8b56-64d168f026d7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
