<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Bt_Home</name>
   <tag></tag>
   <elementGuidId>e5cb0a79-3cdd-4ea6-9e65-7faf98eac39f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.VHreRh.kHGn_J.XjRT60.bCyBlM</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@data-test-id='pinterest-logo-home-button']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>[data-test-id=&quot;pinterest-logo-home-button&quot;] >> internal:role=link[name=&quot;Home&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>688081b3-3df1-4035-81ea-28442cc8cbd8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>VHreRh kHGn_J XjRT60 bCyBlM</value>
      <webElementGuid>9d11a5a4-c5e8-4a8b-b0ff-e6e8bc9dbe8e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;VerticalNavContent&quot;)/div[@class=&quot;ADXRXN _xSIdT&quot;]/div[@class=&quot;ADXRXN _tKaHB qJUqe1 sSBu24 zEVE_X&quot;]/div[@class=&quot;ADXRXN _tKaHB sSBu24 zEVE_X&quot;]/div[@class=&quot;ADXRXN&quot;]/div[@class=&quot;ADXRXN&quot;]/div[@class=&quot;ADXRXN DTsIgD&quot;]/div[@class=&quot;ADXRXN&quot;]/a[@class=&quot;etmDmh i7jpet zlD4hU Q3hcOU O0u6sV dVx3J_ mm_g7v&quot;]/div[@class=&quot;VHreRh kHGn_J XjRT60 bCyBlM&quot;]</value>
      <webElementGuid>098cebff-35dd-4abe-a74e-adb9f410a958</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value></value>
      <webElementGuid>a090d088-2fea-4fa8-b70c-50a860ec0d84</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value></value>
      <webElementGuid>37e6c225-2a9e-4160-81cb-209c2d591027</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value></value>
      <webElementGuid>f1f70901-885a-405f-9e72-303dc274d3ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value></value>
      <webElementGuid>c6aa03fe-87bb-4faf-b246-d3df4cce1a26</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value></value>
      <webElementGuid>68dc3000-4d3f-4768-a6f4-7008867e9bf3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
