<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Bt_Create board</name>
   <tag></tag>
   <elementGuidId>1dcdab5d-72e0-4c3a-9212-dad023a17d9c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.ADXRXN.MQHiAK._HYyJc.dHA5K0.h2QNmC</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@role='button' and .//text()='Create board']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>[data-test-id=&quot;create-board-button&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>b08f6b74-f07f-48d6-b301-edd55ddf981d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ADXRXN MQHiAK _HYyJc dHA5K0 h2QNmC</value>
      <webElementGuid>24361e27-fd5e-4c44-9906-b5cdfaf5ecdc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;_r_2_&quot;)/div[@class=&quot;ADXRXN WTrvgR dHA5K0 ecEhnF&quot;]/div[@class=&quot;H2DtUH KwViV7 FE_3R1 Tjcf3c&quot;]/div[1]/div[@class=&quot;ADXRXN gEQpi5&quot;]/div[@class=&quot;ADXRXN Tjcf3c zEVE_X&quot;]/div[@class=&quot;H2DtUH KwViV7 FE_3R1 KDGhSV _tKaHB qtP9fl&quot;]/div[@class=&quot;ADXRXN WTrvgR lSnwe8&quot;]/div[@class=&quot;ADXRXN dHA5K0 zEVE_X&quot;]/div[@class=&quot;Q3hcOU dHA5K0 O0u6sV itw4K9 g0I6wi be_g_n ap8aAM&quot;]/div[@class=&quot;ADXRXN BVzdUh _xSIdT h2QNmC sSBu24 zEVE_X&quot;]/div[@class=&quot;ADXRXN MQHiAK _HYyJc dHA5K0 h2QNmC&quot;]</value>
      <webElementGuid>0a8d4299-a044-42e4-8a6d-945679c082ef</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value></value>
      <webElementGuid>01d68ceb-85dc-4155-88f2-3fdcb17ba4e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value></value>
      <webElementGuid>42e3a3e9-ad35-4e73-9a10-6dd65bb2a759</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value></value>
      <webElementGuid>6e55a925-74ee-47d2-8419-2079177302c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value></value>
      <webElementGuid>ca3e05fc-7e01-46c6-b00d-fab5e84b8171</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value></value>
      <webElementGuid>5981a313-b392-4c3f-ac57-2c2ada72c7fa</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
