<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_BoardName</name>
   <tag></tag>
   <elementGuidId>9f385e0e-89e6-40d7-8fb1-8e54bb1b22a5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='board-name']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#board-name</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Name your board&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>17373674-baec-420d-b26c-17404456c414</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>facdc94b-f83d-4157-877b-51175d5c99f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>VTVmV8 q3kIpX g0zfi1 bb8HPP zNJ6Me c3eeZM vr41LG EYma4O hxKTA7 mm0O_j eyoFbE glzo1E btwCoE</value>
      <webElementGuid>9c87b878-6f38-4639-8029-4b5a759a0a0a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>board-name</value>
      <webElementGuid>14ede249-6d57-4331-a68c-ed15063cd103</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Name your board</value>
      <webElementGuid>f40581ea-d4d6-451c-a519-141ed68e5c25</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>310ba1b3-ea58-4e2e-ac27-b6639c794013</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>boardName</value>
      <webElementGuid>9d7f04ec-1070-4a9c-a7cd-c195f8e79078</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;board-name&quot;)</value>
      <webElementGuid>fe4384c5-6b3b-4622-a618-71ab316d5f33</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='board-name']</value>
      <webElementGuid>b60bb972-7082-4d68-9e37-d0a9c8275c51</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='board-create-glowup-form']/div/div/div[2]/div/div/input</value>
      <webElementGuid>56b1759f-55f9-4b18-b634-109678e691d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/input</value>
      <webElementGuid>b5b931ef-f7b2-48f5-9511-c99636329120</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'board-name' and @placeholder = 'Name your board' and @type = 'text' and @name = 'boardName']</value>
      <webElementGuid>38e5a330-1c51-41c1-973e-5040b847aa5f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
