<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Pin</name>
   <tag></tag>
   <elementGuidId>72b7f813-6d41-446b-b186-6931153e158c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//img[contains(@src,'pinimg')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.ADXRXN > div.ADXRXN.gEQpi5 > img.iFOUS5</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Story pin image&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>47edd28c-2459-407a-86c1-6f5204b14173</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Story pin image</value>
      <webElementGuid>2c32be8c-807a-4d6d-a643-832b2f147f04</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>iFOUS5</value>
      <webElementGuid>8df586e8-ed71-4596-8cae-659dd041137b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>draggable</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>339af37d-80a4-4be9-8874-30859300b33e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>fetchpriority</name>
      <type>Main</type>
      <value>high</value>
      <webElementGuid>563d6c23-0fd5-4fbc-9890-7cad96c6b261</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>loading</name>
      <type>Main</type>
      <value>auto</value>
      <webElementGuid>9cd8d9d5-1642-457b-a02c-65705da65792</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>elementtiming</name>
      <type>Main</type>
      <value>StoryPinImageBlock-MainPinImage</value>
      <webElementGuid>75725b52-1eee-4dc9-81dc-02e5cc0e7407</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://i.pinimg.com/736x/83/ed/24/83ed246c531f712d8edf2090e98b9c49.jpg</value>
      <webElementGuid>651c9401-cee3-418d-a02b-ede7535ba331</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;gradient&quot;)/div[@class=&quot;ADXRXN&quot;]/div[@class=&quot;ADXRXN _tKaHB ecEhnF zEVE_X&quot;]/div[@class=&quot;ADXRXN wl0pCr&quot;]/div[@class=&quot;ADXRXN XC5OnJ gEQpi5&quot;]/div[@class=&quot;ADXRXN&quot;]/div[@class=&quot;ADXRXN gEQpi5&quot;]/div[@class=&quot;ADXRXN BVzdUh ecEhnF gEQpi5 zEVE_X&quot;]/div[@class=&quot;ADXRXN&quot;]/div[@class=&quot;H2DtUH KwViV7 FE_3R1 KDGhSV Tjcf3c qtP9fl&quot;]/div[@class=&quot;H2DtUH KwViV7 FE_3R1 _tKaHB wl0pCr&quot;]/div[@class=&quot;ADXRXN AzXCPS KDGhSV ZEBTif _tKaHB qtP9fl zEVE_X&quot;]/div[@class=&quot;ADXRXN&quot;]/div[@class=&quot;ADXRXN&quot;]/div[@class=&quot;ADXRXN _tKaHB gEQpi5 kF2VEF zEVE_X&quot;]/div[@class=&quot;ADXRXN&quot;]/div[@class=&quot;ADXRXN gcIrSY&quot;]/div[@class=&quot;ADXRXN AzXCPS gEQpi5&quot;]/div[@class=&quot;Q3hcOU DodKMr BM2pT6 itw4K9 g0I6wi&quot;]/div[@class=&quot;ADXRXN&quot;]/div[@class=&quot;ADXRXN&quot;]/div[@class=&quot;ADXRXN TfR6nu WTrvgR&quot;]/div[@class=&quot;ADXRXN WTrvgR&quot;]/div[@class=&quot;ADXRXN&quot;]/div[@class=&quot;ADXRXN gEQpi5&quot;]/img[@class=&quot;iFOUS5&quot;]</value>
      <webElementGuid>42495869-de8b-42c7-adef-12c68b0eee66</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value></value>
      <webElementGuid>f0eb0f9b-7524-43b7-95d4-0bffc42f3a05</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value></value>
      <webElementGuid>0c53aa29-3272-4e04-9831-1a7000f2a715</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value></value>
      <webElementGuid>8bdc6c1b-9c9b-4000-add0-bf9018916470</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value></value>
      <webElementGuid>e0e18da1-df59-49da-9146-de062ae126bf</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
