<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_BoardContainer</name>
   <tag></tag>
   <elementGuidId>039635e7-2028-45c7-9285-25a1f4a45d76</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__PWS_ROOT__']/div/div/div[3]/div/div/div/div/div[2]/div/div/div/div/div/div/div/div/div/div/div/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.KnPdox.gEQpi5</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Ava, 161 Pins, 4hMeow, 50 Pins, 5hDouyin ava, 21 Pins, 2dCortis, 281 Pins, 3dbac&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>60701fce-d6ee-440a-915b-bcaae12758ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>KnPdox gEQpi5</value>
      <webElementGuid>b6f717f4-1d14-4727-9c5a-a373c626da0d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>list</value>
      <webElementGuid>72525b9f-0b2c-4ce9-80b2-444ad28de77f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Ava, 161 Pins, 4hMeow, 50 Pins, 5hDouyin ava, 21 Pins, 2dCortis, 281 Pins, 3dbackground, 41 Pins, 3wNeko choan~, , 3 Pins, 2modiscord, 22 Pins, 3morepost, 1 Pin, 7mocover photos, 22 Pins, 7momakeup, 10 Pins, 1youtfit, 9 Pins, 1yhairstyle, 1 Pin, 2y</value>
      <webElementGuid>3c68684c-9644-4ea2-ba4f-2c68e19fa20d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__PWS_ROOT__&quot;)/div[@class=&quot;ADXRXN&quot;]/div[@class=&quot;ADXRXN&quot;]/div[@class=&quot;appContent&quot;]/div[@class=&quot;ADXRXN&quot;]/div[@class=&quot;mainContainer&quot;]/div[@class=&quot;ADXRXN&quot;]/div[@class=&quot;ADXRXN&quot;]/div[@class=&quot;ADXRXN&quot;]/div[@class=&quot;H2DtUH KwViV7 z6WAHi _tKaHB&quot;]/div[@class=&quot;oRZ5_s&quot;]/div[@class=&quot;ADXRXN&quot;]/div[@class=&quot;ADXRXN Emc7hI&quot;]/div[@class=&quot;ADXRXN WTrvgR&quot;]/div[@class=&quot;ADXRXN&quot;]/div[1]/div[@class=&quot;masonryContainer&quot;]/div[@class=&quot;m_t16f236162&quot;]/div[@class=&quot;ADXRXN MEP_vB XC5OnJ aNs6gM iHQedX&quot;]/div[1]/div[@class=&quot;KnPdox gEQpi5&quot;]</value>
      <webElementGuid>83f5f440-ffc2-45c1-a62a-6922d3cd7002</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__PWS_ROOT__']/div/div/div[3]/div/div/div/div/div[2]/div/div/div/div/div/div/div/div/div/div/div/div</value>
      <webElementGuid>5ca50353-3f6c-4b1c-9ee3-c8a9798487a0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Create'])[1]/following::div[13]</value>
      <webElementGuid>7dc5f0b4-6a8e-4017-a2d9-69c888ef6122</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Secret'])[1]/following::div[20]</value>
      <webElementGuid>cde051fe-2385-42ea-8d06-ba957cc0b7d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/div/div/div/div/div/div/div/div</value>
      <webElementGuid>75962bff-5fd2-4c89-abdc-5658cc479b07</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Ava, 161 Pins, 4hMeow, 50 Pins, 5hDouyin ava, 21 Pins, 2dCortis, 281 Pins, 3dbackground, 41 Pins, 3wNeko choan~, , 3 Pins, 2modiscord, 22 Pins, 3morepost, 1 Pin, 7mocover photos, 22 Pins, 7momakeup, 10 Pins, 1youtfit, 9 Pins, 1yhairstyle, 1 Pin, 2y' or . = 'Ava, 161 Pins, 4hMeow, 50 Pins, 5hDouyin ava, 21 Pins, 2dCortis, 281 Pins, 3dbackground, 41 Pins, 3wNeko choan~, , 3 Pins, 2modiscord, 22 Pins, 3morepost, 1 Pin, 7mocover photos, 22 Pins, 7momakeup, 10 Pins, 1youtfit, 9 Pins, 1yhairstyle, 1 Pin, 2y')]</value>
      <webElementGuid>a7de04b8-4d3f-428a-b663-ac8cedc851f7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
