<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Push_switch</name>
   <tag></tag>
   <elementGuidId>b62bb70f-69b3-4047-b0d1-b37d053d694f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#switch-push</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='switch-push']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Push&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a4338980-31a8-43ca-9183-00666c588ea5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>b4JET0 vwgzs2</value>
      <webElementGuid>16c0094d-6b12-4ccf-baea-2536f32f80fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>switch-push</value>
      <webElementGuid>1d992d10-facb-47eb-89db-365ee8ddbf85</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>b395600c-be01-4fc3-857c-f572a839948e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;switch-push&quot;)</value>
      <webElementGuid>e94d41c6-5e73-4f7c-b12c-55037e95a209</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='switch-push']</value>
      <webElementGuid>453ab9ed-68fa-4e7b-b0ab-85413c590601</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__PWS_ROOT__']/div/div/div[3]/div/div/div/div[2]/div/div[2]/div[2]/div[9]/div[2]/div/div[2]/div/div/div/div[2]/div/div/input</value>
      <webElementGuid>c254c701-553f-4ced-9b22-a647edda8817</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/input</value>
      <webElementGuid>31fff119-ed51-4cc4-9d24-5262b71602cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'switch-push' and @type = 'checkbox']</value>
      <webElementGuid>e73f49d3-16dd-412c-b21b-1217774ee0c2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
