<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Email_switch</name>
   <tag></tag>
   <elementGuidId>ed9d7d90-c564-47aa-9ef6-7ce485d788bb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#switch-email</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='switch-email']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Email&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a9c9bf8f-b928-482c-b2a6-e6bd6d263bdf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>b4JET0 vwgzs2</value>
      <webElementGuid>898bb67c-2fe0-454b-8731-4538a3a372b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>switch-email</value>
      <webElementGuid>cba6cf7f-ef7e-4284-b735-3559545580bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>5f901b88-ccf2-4e80-a8c0-6bb81b610593</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;switch-email&quot;)</value>
      <webElementGuid>0d254f42-f9fc-451e-93bf-09795faa0e82</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='switch-email']</value>
      <webElementGuid>a38d6dd3-4e9a-48de-a68f-c30388e8256f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__PWS_ROOT__']/div/div/div[3]/div/div/div/div[2]/div/div[2]/div[2]/div[9]/div[2]/div/div[2]/div[2]/div/div/div[2]/div/div/input</value>
      <webElementGuid>10951f0d-a952-4f4e-b6eb-47fdeeaaab1a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div[2]/div/div/input</value>
      <webElementGuid>63d088ee-b3bd-4593-99e1-9d3c60c1e4a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'switch-email' and @type = 'checkbox']</value>
      <webElementGuid>a6074053-d416-4f1e-8ac2-d9c218501015</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
