<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Bt_Share</name>
   <tag></tag>
   <elementGuidId>cf11e380-664f-493f-8472-bd30f7e79d19</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.VHreRh.kHGn_J.cUw_ba.bCyBlM</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@data-test-id='closeup-share-button']//button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Send&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>14ca8443-7281-4857-ba1c-63c5d648cf76</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>VHreRh kHGn_J cUw_ba bCyBlM</value>
      <webElementGuid>b813cb6c-b022-4f89-8e99-c165cb0ae38d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;gradient&quot;)/div[@class=&quot;ADXRXN&quot;]/div[@class=&quot;ADXRXN _tKaHB ecEhnF zEVE_X&quot;]/div[@class=&quot;ADXRXN wl0pCr&quot;]/div[@class=&quot;ADXRXN XC5OnJ gEQpi5&quot;]/div[@class=&quot;ADXRXN&quot;]/div[@class=&quot;ADXRXN gEQpi5&quot;]/div[@class=&quot;ADXRXN BVzdUh ecEhnF gEQpi5 zEVE_X&quot;]/div[@class=&quot;ADXRXN&quot;]/div[@class=&quot;H2DtUH KwViV7 FE_3R1 KDGhSV Tjcf3c qtP9fl&quot;]/div[@class=&quot;H2DtUH KwViV7 FE_3R1 _tKaHB wl0pCr&quot;]/div[@class=&quot;ADXRXN AzXCPS KDGhSV ZEBTif _tKaHB qtP9fl zEVE_X&quot;]/div[@class=&quot;ADXRXN BVzdUh Yh17xG dSlwuX kF2VEF sSBu24 zEVE_X&quot;]/div[@class=&quot;ADXRXN ecEhnF iHQedX&quot;]/div[@class=&quot;ADXRXN&quot;]/div[@class=&quot;H2DtUH KwViV7 FE_3R1 Tjcf3c qJUqe1 qtP9fl&quot;]/div[@class=&quot;ADXRXN dHA5K0 qJUqe1 qzrGlv sSBu24 zEVE_X&quot;]/div[@class=&quot;H2DtUH c1Gamg z6WAHi KDGhSV Tjcf3c qtP9fl&quot;]/div[@class=&quot;oRZ5_s&quot;]/div[@class=&quot;ADXRXN&quot;]/div[@class=&quot;ADXRXN&quot;]/div[@class=&quot;ADXRXN&quot;]/div[@class=&quot;ADXRXN nnftW_&quot;]/div[@class=&quot;ADXRXN&quot;]/div[@class=&quot;ADXRXN&quot;]/div[@class=&quot;H2DtUH KwViV7 FE_3R1 KDGhSV Tjcf3c sSBu24&quot;]/button[@class=&quot;euRXRl&quot;]/div[@class=&quot;dVx3J_ Q3hcOU mm_g7v&quot;]/div[@class=&quot;VHreRh kHGn_J cUw_ba bCyBlM&quot;]</value>
      <webElementGuid>4cbba4a4-98ed-453a-b77e-444583fa9505</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value></value>
      <webElementGuid>fb6291a3-d917-447e-b914-fc4889d7b094</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value></value>
      <webElementGuid>522d8201-cf79-499e-a71d-00818b27c93e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value></value>
      <webElementGuid>ee008a99-50b0-4f5e-87af-715e57ce3d10</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value></value>
      <webElementGuid>ea141343-609d-4df9-b599-d0a0e1ca39e6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value></value>
      <webElementGuid>9c3e1746-f20a-4f5e-be9a-be3cddc5b590</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value></value>
      <webElementGuid>66999224-09f5-4ce3-b11f-57edc7d35c7e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
