<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Bt_Delete</name>
   <tag></tag>
   <elementGuidId>49acf87d-0712-4e68-bc05-f380639242b7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.VHreRh.kHGn_J.o_L6IZ.bCyBlM</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@aria-label='Delete Pins']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>be5114ff-9c25-49f4-a733-1970a53d44e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>VHreRh kHGn_J o_L6IZ bCyBlM</value>
      <webElementGuid>3b3c0bd7-0fd7-457f-bbde-2b15df00468b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__PWS_ROOT__&quot;)/div[@class=&quot;ADXRXN&quot;]/div[@class=&quot;ADXRXN&quot;]/div[@class=&quot;appContent&quot;]/div[@class=&quot;ADXRXN&quot;]/div[@class=&quot;mainContainer&quot;]/div[@class=&quot;ADXRXN&quot;]/div[@class=&quot;ADXRXN NYgy1O OxdK06 n62I2n&quot;]/div[@class=&quot;H2DtUH c1Gamg FE_3R1 Tjcf3c kF2VEF sSBu24&quot;]/div[@class=&quot;oRZ5_s&quot;]/div[@class=&quot;ADXRXN ecEhnF gcIrSY lSnwe8&quot;]/div[@class=&quot;ADXRXN DTsIgD&quot;]/div[@class=&quot;ADXRXN&quot;]/button[@class=&quot;euRXRl&quot;]/div[@class=&quot;dVx3J_ Q3hcOU mm_g7v&quot;]/div[@class=&quot;VHreRh kHGn_J o_L6IZ bCyBlM&quot;]</value>
      <webElementGuid>d006c63c-1451-4b8f-9840-e17ec8b5606d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value></value>
      <webElementGuid>688a4981-c661-467d-8325-838efcc8c715</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value></value>
      <webElementGuid>8bc9438d-9b64-4986-8271-9b352db4c644</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value></value>
      <webElementGuid>402d347a-4f13-4157-a414-cf47726931d6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value></value>
      <webElementGuid>e96d0d86-f143-4dbf-881b-92ea4cae6acd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value></value>
      <webElementGuid>119a07f6-4f4d-42a0-a86b-29f111f6066c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
