<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Pin1</name>
   <tag></tag>
   <elementGuidId>3a61d794-a839-4665-bef2-5389e80617a8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.Q3hcOU.dHA5K0.O0u6sV.BM2pT6.itw4K9.g0I6wi.be_g_n.ap8aAM</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//div[@aria-label='Drag and drop deselected item' and @role='button'])[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>2f69c1a3-26f1-44ed-b0e8-ad4b833e79a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>cd2ab991-4a3e-490e-9951-f204affaa15b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Drag and drop deselected item</value>
      <webElementGuid>5fa4a599-8e69-4380-a521-39bd3c69a8dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>Q3hcOU dHA5K0 O0u6sV BM2pT6 itw4K9 g0I6wi be_g_n ap8aAM</value>
      <webElementGuid>905c3546-1165-4607-8776-1657d06552e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>4f4e005e-82ef-483b-a51f-74e2cd28e9d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>c5d86fc5-1d4b-42b4-8789-1e9204dc83ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__PWS_ROOT__&quot;)/div[@class=&quot;ADXRXN&quot;]/div[@class=&quot;ADXRXN&quot;]/div[@class=&quot;appContent&quot;]/div[@class=&quot;ADXRXN&quot;]/div[@class=&quot;mainContainer&quot;]/div[@class=&quot;ADXRXN&quot;]/div[@class=&quot;ADXRXN Emc7hI&quot;]/div[@class=&quot;ADXRXN gEQpi5 gHrR3r&quot;]/div[@class=&quot;ADXRXN&quot;]/div[1]/div[@class=&quot;masonryContainer&quot;]/div[@class=&quot;m_t16f221252&quot;]/div[@class=&quot;ADXRXN MEP_vB XC5OnJ aNs6gM iHQedX&quot;]/div[1]/div[@class=&quot;KnPdox gEQpi5&quot;]/div[@class=&quot;V3gVHw TfR6nu v65fHc&quot;]/div[1]/div[@class=&quot;ADXRXN&quot;]/div[@class=&quot;ADXRXN&quot;]/div[@class=&quot;ADXRXN&quot;]/div[1]/div[@class=&quot;ADXRXN gEQpi5&quot;]/div[@class=&quot;ADXRXN NYgy1O TfR6nu aHn_t7 bnBtRO mJ2PyB&quot;]/div[@class=&quot;Q3hcOU dHA5K0 O0u6sV BM2pT6 itw4K9 g0I6wi be_g_n ap8aAM&quot;]</value>
      <webElementGuid>7a419a39-67b1-4bb1-bdd2-9ceee4a38788</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value></value>
      <webElementGuid>44f2c3c4-14f7-4780-b29b-aa43eb2e09a5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value></value>
      <webElementGuid>9ccabb69-1710-4898-8643-adc7e4fd67d2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
