<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Bt_Organize</name>
   <tag></tag>
   <elementGuidId>8fceb12b-e854-4230-8ec1-15089afcbf59</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.ADXRXN.AzXCPS.g8WGSl.kF2VEF.sSBu24.zEVE_X</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@data-test-id='Organize']//a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>cfeee279-7af7-4be2-9062-0b850c984025</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ADXRXN AzXCPS g8WGSl kF2VEF sSBu24 zEVE_X</value>
      <webElementGuid>c94a95c9-71f4-497b-884d-968e2dc8b25b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__PWS_ROOT__&quot;)/div[@class=&quot;ADXRXN&quot;]/div[@class=&quot;ADXRXN&quot;]/div[@class=&quot;appContent&quot;]/div[@class=&quot;ADXRXN&quot;]/div[@class=&quot;mainContainer&quot;]/div[@class=&quot;ADXRXN&quot;]/div[@class=&quot;ADXRXN&quot;]/div[@class=&quot;ADXRXN gSktR2&quot;]/div[@class=&quot;ADXRXN _tKaHB djbjbM zEVE_X&quot;]/div[@class=&quot;ADXRXN LbyOQL gSktR2&quot;]/div[@class=&quot;boardFeedAlignmentWrapper&quot;]/div[@class=&quot;H2DtUH KwViV7 FE_3R1 Tjcf3c hVtwEZ qJUqe1&quot;]/div[@class=&quot;ADXRXN&quot;]/div[@class=&quot;H2DtUH l3eg_b iUXl9c KDGhSV _tKaHB hVtwEZ&quot;]/div[@class=&quot;oRZ5_s&quot;]/div[@class=&quot;ADXRXN&quot;]/div[@class=&quot;H2DtUH KwViV7 FE_3R1 Tjcf3c hVtwEZ kF2VEF&quot;]/div[@class=&quot;ADXRXN DgJbZ_ ylMNj8&quot;]/a[@class=&quot;etmDmh i7jpet zlD4hU Q3hcOU g8WGSl O0u6sV KQwCbH itw4K9 g0I6wi be_g_n ap8aAM&quot;]/div[@class=&quot;ADXRXN _tKaHB kF2VEF zEVE_X&quot;]/div[@class=&quot;ADXRXN AzXCPS g8WGSl kF2VEF sSBu24 zEVE_X&quot;]</value>
      <webElementGuid>8503ad77-6dce-4c32-adbf-b2cc85ea9944</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value></value>
      <webElementGuid>12ca4935-ef83-4ac6-a11c-f5b8707449e2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value></value>
      <webElementGuid>d6f2eaab-e6d8-4aa9-bc7d-db5ccb986144</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value></value>
      <webElementGuid>1b3e2e69-0e8e-4a02-90cf-b6097b7243d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value></value>
      <webElementGuid>ab153455-ec18-4bc9-b112-bd506aa59c33</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value></value>
      <webElementGuid>4fcb40c6-6a15-475c-97b6-fdffecf0570b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value></value>
      <webElementGuid>a00661e3-2b30-4002-ad5a-299e10ee352a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
