<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_BoardMeow_Container</name>
   <tag></tag>
   <elementGuidId>879c5091-ea86-4336-b904-5e294b969345</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.KnPdox.gEQpi5</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@data-test-id='board-feed']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;\&quot;What ??? Shocked cat Sticker \&quot; Magnet by Noor-alhuda | Redbubbletổng hợp meme h&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>2e5dca7f-37af-462a-9b24-addb37723c24</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>KnPdox gEQpi5</value>
      <webElementGuid>ce45ffb6-a20e-4d53-99b1-cdc742de9dc4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>list</value>
      <webElementGuid>f4c2ffc3-b29d-40d5-88ec-a494018df53a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>&quot;What ??? Shocked cat Sticker &quot; Magnet by Noor-alhuda | Redbubbletổng hợp meme hài hước vô tri</value>
      <webElementGuid>40770b5d-a1c4-44e5-a307-cca2f728e6a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__PWS_ROOT__&quot;)/div[@class=&quot;ADXRXN&quot;]/div[@class=&quot;ADXRXN&quot;]/div[@class=&quot;appContent&quot;]/div[@class=&quot;ADXRXN&quot;]/div[@class=&quot;mainContainer&quot;]/div[@class=&quot;ADXRXN&quot;]/div[@class=&quot;ADXRXN&quot;]/div[@class=&quot;ADXRXN&quot;]/div[@class=&quot;ADXRXN Emc7hI&quot;]/div[@class=&quot;ADXRXN gEQpi5 gHrR3r&quot;]/div[@class=&quot;ADXRXN&quot;]/div[1]/div[@class=&quot;masonryContainer&quot;]/div[@class=&quot;m_t16f221252&quot;]/div[@class=&quot;ADXRXN MEP_vB XC5OnJ aNs6gM iHQedX&quot;]/div[1]/div[@class=&quot;KnPdox gEQpi5&quot;]</value>
      <webElementGuid>74f30763-671a-4226-ab8c-469290bbba13</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value></value>
      <webElementGuid>603eaefa-7635-4a07-8a45-1a44d326637a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value></value>
      <webElementGuid>e85d3736-d03d-4cfc-bfcd-942918cadab5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value></value>
      <webElementGuid>b6dd0672-5036-41ad-bd82-2b46c2d02bba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value></value>
      <webElementGuid>9edd64e4-e1b7-40aa-993f-6e9822c5813e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value></value>
      <webElementGuid>7c5dbdb0-4bdf-4d84-9435-2eacf3c53120</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
