<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Change Password</name>
   <tag></tag>
   <elementGuidId>564e7769-75a9-4094-899c-7e4f154c3226</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.G0yGFD.ap8aAM.Q3hcOU.gwpqhu.itmoZr.GaMK1V.O0u6sV</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[.//div[text()='Change Password']]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Change Password&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>896110be-fb8d-491e-8809-b4a5b424f0af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>G0yGFD ap8aAM Q3hcOU gwpqhu itmoZr GaMK1V O0u6sV</value>
      <webElementGuid>a9d48349-4aa4-455f-897e-ee605c04ca8b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>b6c951e4-0072-4a50-9674-6081ce0d323f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>1529a9c1-63c7-45b5-9c21-cadab018bb6d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Change Password</value>
      <webElementGuid>8a6d5671-0a75-4e7e-8eeb-e47fb8098c96</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;en&quot;]/body[1]/div[@class=&quot;unzjra&quot;]/div[1]/div[1]/div[@class=&quot;asf_Xx&quot;]/div[@class=&quot;YLPkP_ j3H91d c0G7To&quot;]/div[@class=&quot;ADXRXN _tKaHB gEQpi5 wl0pCr zEVE_X&quot;]/div[@class=&quot;ADXRXN dDmW3o gEQpi5&quot;]/div[@class=&quot;ADXRXN CQ1_jt b6DHg3&quot;]/div[@class=&quot;ADXRXN _VU9d3 kXGpvW sSBu24 xdjfP5 zEVE_X&quot;]/div[@class=&quot;ADXRXN ylMNj8&quot;]/button[@class=&quot;G0yGFD ap8aAM Q3hcOU gwpqhu itmoZr GaMK1V O0u6sV&quot;]</value>
      <webElementGuid>7bfbe7e1-9599-427f-9ecd-a6400830d061</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value></value>
      <webElementGuid>2a9b72f8-066c-4a4e-b5a2-4bbb64c9a763</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value></value>
      <webElementGuid>0f3ce664-43dd-4491-a576-8625ec78763e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value></value>
      <webElementGuid>c89b2499-7087-4c36-993a-6d859c510ffe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value></value>
      <webElementGuid>2cfbb3f2-6ae6-4e10-a019-53bb05a454d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value></value>
      <webElementGuid>e57c1eab-30ac-4c03-b9ca-f264f50de11c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
