<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_OldPassword</name>
   <tag></tag>
   <elementGuidId>36dba2b0-96f0-4e88-bbd9-15ca5155be84</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#changePasswordOld</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='changePasswordOld']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Old password&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a382e1f1-fe35-4f08-91fa-de6c67052345</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>18deadea-6160-40b6-87e6-932ad5c8f940</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>current-password</value>
      <webElementGuid>8e153848-e617-4068-99a0-3b97dda0451a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>VTVmV8 q3kIpX g0zfi1 bb8HPP zNJ6Me c3eeZM vr41LG EYma4O hxKTA7 mm0O_j VpxGtC glzo1E hPj47J</value>
      <webElementGuid>993d3115-4ddc-4075-9acb-0da72c594322</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>changePasswordOld</value>
      <webElementGuid>20bdd812-41a3-4318-8042-f2b36fc02fec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>spellcheck</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>ee6769d2-687d-4258-ad1a-585306715dee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>aab46d8c-66e4-4b49-a05b-0c5f634d5f2e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>old</value>
      <webElementGuid>4ca3b930-aaee-40ed-8a13-4fa7a7c6cd48</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>T12345678</value>
      <webElementGuid>9c91e2a7-89d6-49ce-b2bd-e34f8f585431</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;changePasswordOld&quot;)</value>
      <webElementGuid>a2cb0dba-bcb0-4989-bf4e-56903b425377</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='changePasswordOld']</value>
      <webElementGuid>0874bb24-bb5e-4e93-af55-8e3d40ee4974</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/input</value>
      <webElementGuid>e22588c9-21bf-444f-8ff6-8a2bd6676cf5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'changePasswordOld' and @type = 'password' and @name = 'old']</value>
      <webElementGuid>17dee264-fee7-466d-9555-47091fddf47d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
