<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Profiles</name>
   <tag></tag>
   <elementGuidId>1d3f56e3-79bb-4fbd-a41d-76d5fb78afb8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@data-test-id='single-select-radio-3']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Profiles&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>ef77016a-7a96-4656-9844-996b68a202bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>H2DtUH KwViV7 FE_3R1 Tjcf3c sSBu24</value>
      <webElementGuid>9b8de681-e87e-4697-8c2a-cb9a7cdd7b28</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Profiles</value>
      <webElementGuid>a207338d-bffe-4d33-a944-fcdc79c80c5c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;search_filters_drawer&quot;)/div[@class=&quot;ADXRXN&quot;]/div[@class=&quot;ADXRXN DgJbZ_ drGcEU gEQpi5 ylMNj8&quot;]/div[@class=&quot;ADXRXN _xSIdT&quot;]/div[@class=&quot;ADXRXN&quot;]/fieldset[@class=&quot;spwtVl&quot;]/div[@class=&quot;H2DtUH KwViV7 z6WAHi _tKaHB&quot;]/div[@class=&quot;oRZ5_s&quot;]/div[@class=&quot;xYReI2&quot;]/div[@class=&quot;ADXRXN BGUL9_&quot;]/div[@class=&quot;H2DtUH KwViV7 dx7iHa _tKaHB&quot;]/div[@class=&quot;oRZ5_s&quot;]/div[@class=&quot;Q3hcOU DodKMr O0u6sV itw4K9 g0I6wi be_g_n ap8aAM&quot;]/div[@class=&quot;ADXRXN&quot;]/div[@class=&quot;H2DtUH KwViV7 FE_3R1 Tjcf3c sSBu24&quot;]</value>
      <webElementGuid>2cd851cf-66db-4fd4-9f76-9db6cd50a2c7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value></value>
      <webElementGuid>80d1eeae-ca8e-4442-8cb6-f781634b486f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value></value>
      <webElementGuid>5bcd9595-c4be-417a-8e33-0ec9031af0d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value></value>
      <webElementGuid>b3a3fc97-aee0-476b-ab0f-4dae478d20f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value></value>
      <webElementGuid>d982d632-0819-49e4-bd7d-ee658e5be027</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value></value>
      <webElementGuid>23970bb5-b950-4c3b-b062-232a0be32a1f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value></value>
      <webElementGuid>d277fe16-c05a-43c3-807a-d4c811b87eb8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
