<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Bt_Follow</name>
   <tag></tag>
   <elementGuidId>88cfa6fd-0307-4a3e-b981-3ad54e98fbcd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.dBMCN4.jShAKf.iS__OQ.RABojg._W0I5h.yVbCXY.UOJS4b.y4A0gb.ap8aAM.O0u6sV</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@data-test-id='user-follow-button']//button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Follow&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>dae19f81-49a9-45e3-b5f8-6b2a0aaefb46</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dBMCN4 jShAKf iS__OQ RABojg _W0I5h yVbCXY UOJS4b y4A0gb ap8aAM O0u6sV</value>
      <webElementGuid>3ec72bc5-4171-4d3a-ae30-53c0d4f5b593</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Follow</value>
      <webElementGuid>aa12a4f4-86cb-4564-80a1-9dae3f79e442</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__PWS_ROOT__&quot;)/div[@class=&quot;ADXRXN&quot;]/div[@class=&quot;ADXRXN&quot;]/div[@class=&quot;appContent&quot;]/div[@class=&quot;ADXRXN&quot;]/div[@class=&quot;mainContainer&quot;]/div[@class=&quot;ADXRXN&quot;]/div[@class=&quot;ADXRXN&quot;]/div[@class=&quot;ADXRXN SKA4an kF2VEF zEVE_X&quot;]/div[@class=&quot;ADXRXN EH8C6E&quot;]/div[@class=&quot;H2DtUH KwViV7 z6WAHi _tKaHB kF2VEF sSBu24&quot;]/div[@class=&quot;oRZ5_s&quot;]/div[@class=&quot;ADXRXN&quot;]/div[@class=&quot;H2DtUH jc60H4 FE_3R1 Tjcf3c&quot;]/div[@class=&quot;oRZ5_s&quot;]/div[@class=&quot;H2DtUH c1Gamg FE_3R1 KDGhSV Tjcf3c sSBu24&quot;]/div[@class=&quot;oRZ5_s&quot;]/div[@class=&quot;ADXRXN gEQpi5 zEVE_X&quot;]/div[@class=&quot;ADXRXN&quot;]/button[@class=&quot;fsprMd _W0I5h O0u6sV&quot;]/div[@class=&quot;dBMCN4 jShAKf iS__OQ RABojg _W0I5h yVbCXY UOJS4b y4A0gb ap8aAM O0u6sV&quot;]</value>
      <webElementGuid>6aa432c3-e16f-4c46-a72d-e70011732d94</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value></value>
      <webElementGuid>fbeef1b8-61a4-42c2-ba38-004c573bb9be</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value></value>
      <webElementGuid>0b26fd06-637e-4a30-8190-64112a8e7f09</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value></value>
      <webElementGuid>ae173305-bbe4-4d00-a1f3-e138434fceb3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value></value>
      <webElementGuid>2077d2c5-e5cc-453a-8bfe-5a8eabcc2d3c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value></value>
      <webElementGuid>d560fd3c-afdc-49ec-939b-a686a977d5e2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value></value>
      <webElementGuid>289f59e0-7dc9-4196-a7c0-41a9b70ba170</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
