<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Apply</name>
   <tag></tag>
   <elementGuidId>3ba0c3f4-f12a-46c9-838d-c2cfcbf25124</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.lIkAnG.eMU5i5.o5UlW_.h3gMqR.cZLkj_</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@data-test-id='filter-confirm-button']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>[data-test-id=&quot;filter-confirm-button&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>e509b155-3526-48ee-8bef-e47452335ca9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>lIkAnG eMU5i5 o5UlW_ h3gMqR cZLkj_</value>
      <webElementGuid>d7cd5ca9-6612-49ba-ace5-da5c85f18f02</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Apply</value>
      <webElementGuid>36d71b1d-a6c6-4b18-b84b-ed320e9ca812</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;search_filters_drawer&quot;)/div[@class=&quot;ADXRXN&quot;]/div[@class=&quot;ADXRXN NYgy1O TfR6nu k5oQr4&quot;]/div[@class=&quot;ADXRXN ecEhnF kF2VEF zEVE_X&quot;]/div[@class=&quot;ADXRXN C48Khy Tjcf3c zEVE_X&quot;]/div[@class=&quot;ADXRXN RI9PTN&quot;]/button[@class=&quot;G0yGFD ap8aAM Q3hcOU gwpqhu E6J5D_ GaMK1V O0u6sV&quot;]/div[@class=&quot;oxThCB&quot;]/div[@class=&quot;lIkAnG eMU5i5 o5UlW_ h3gMqR cZLkj_&quot;]</value>
      <webElementGuid>7bd06c9b-1851-43ec-99ef-65d16b27410e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value></value>
      <webElementGuid>d8ead1de-abcc-4950-af12-ad5632e2f903</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value></value>
      <webElementGuid>0380d22f-724a-460e-b47b-986244d66f05</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value></value>
      <webElementGuid>03bd8dd8-f7ee-4c61-83eb-c89b6e761d2c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value></value>
      <webElementGuid>665fa187-5bab-45ad-8b74-bc6f5e7f71b0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value></value>
      <webElementGuid>f869cbdc-6272-4f09-8f07-3a2a17ec5821</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value></value>
      <webElementGuid>a9181a09-3430-4a98-a693-4d6742bae41a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value></value>
      <webElementGuid>97669fd1-b1ae-400e-b356-ae88f125e7c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value></value>
      <webElementGuid>e70039d3-c9a7-49d6-a3ce-6dd14b6ccf83</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
