<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Bt_Filter</name>
   <tag></tag>
   <elementGuidId>5e151284-afa3-4a58-bf56-34936217201a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.dBMCN4.jShAKf.iS__OQ.EpMAUU._W0I5h.fAZwDI.SdmY6_.y4A0gb.ap8aAM.O0u6sV</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@data-test-id='one-bar-pill']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>[data-test-id=&quot;one-bar-pill&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>d7846172-28b3-4382-9415-f8c3d90f742a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dBMCN4 jShAKf iS__OQ EpMAUU _W0I5h fAZwDI SdmY6_ y4A0gb ap8aAM O0u6sV</value>
      <webElementGuid>c913eaa3-830e-4987-9f93-4fd68fe16c89</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__PWS_ROOT__&quot;)/div[@class=&quot;ADXRXN&quot;]/div[@class=&quot;ADXRXN&quot;]/div[@class=&quot;appContent&quot;]/div[@class=&quot;ADXRXN&quot;]/div[@class=&quot;mainContainer&quot;]/div[@class=&quot;KvKvqR&quot;]/div[1]/div[@class=&quot;ADXRXN&quot;]/div[@class=&quot;ADXRXN Ip8hrQ ecEhnF gEQpi5&quot;]/div[@class=&quot;ADXRXN gEQpi5 gHrR3r&quot;]/div[@class=&quot;ADXRXN gEQpi5&quot;]/div[@class=&quot;H2DtUH c1Gamg FE_3R1 Tjcf3c sSBu24&quot;]/div[@class=&quot;oRZ5_s&quot;]/div[@class=&quot;ADXRXN&quot;]/div[@class=&quot;ADXRXN&quot;]/div[@class=&quot;ADXRXN&quot;]/div[@class=&quot;ADXRXN gEQpi5&quot;]/button[@class=&quot;fsprMd _W0I5h O0u6sV&quot;]/div[@class=&quot;dBMCN4 jShAKf iS__OQ EpMAUU _W0I5h fAZwDI SdmY6_ y4A0gb ap8aAM O0u6sV&quot;]</value>
      <webElementGuid>cb177db3-56f2-49f0-bb5d-26eb4df84286</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value></value>
      <webElementGuid>12a989be-7f0f-47e8-9ba4-7e8531fc9eaf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value></value>
      <webElementGuid>f0b3f51f-5701-495b-b127-e42fdfe81309</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value></value>
      <webElementGuid>88b248f1-93a8-47c4-9c99-bc199ff88f07</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value></value>
      <webElementGuid>7373bba8-0b42-450b-9010-2f382701470f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value></value>
      <webElementGuid>da7fc8fd-e95a-490e-9e46-a43bdc6370fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value></value>
      <webElementGuid>60d3b01b-3123-419a-bc46-688c335ab06d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
