<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_ReceiveMsg</name>
   <tag></tag>
   <elementGuidId>92286091-ea40-48d6-aa13-26cbb71961a8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@data-test-id='message-item-container']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>d0252185-4d41-4a0e-ae87-57e7a0d7ae85</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ADXRXN g8WGSl h2QNmC</value>
      <webElementGuid>a58868b5-d541-4c3e-8135-f2270ecafa0f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>.</value>
      <webElementGuid>a626529b-d0de-4c0a-9b52-e07fee225105</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;full-height-inbox-panel&quot;)/div[@class=&quot;ADXRXN gEQpi5 gSktR2 i1hWBD&quot;]/div[@class=&quot;H2DtUH KwViV7 FE_3R1 _tKaHB qtP9fl xdjfP5&quot;]/div[@class=&quot;ADXRXN _tKaHB drGcEU zEVE_X&quot;]/div[1]/div[@class=&quot;ADXRXN _tKaHB xdjfP5 zEVE_X&quot;]/div[@class=&quot;ADXRXN C6J6UC gEQpi5 zEVE_X&quot;]/div[@class=&quot;ADXRXN TyRBan _tKaHB gbTsx5 hVtwEZ zEVE_X&quot;]/div[@class=&quot;H2DtUH KwViV7 FE_3R1 KDGhSV Tjcf3c i4_mIm&quot;]/div[@class=&quot;H2DtUH KwViV7 FE_3R1 KDGhSV Tjcf3c qtP9fl wl0pCr&quot;]/div[@class=&quot;ADXRXN&quot;]/div[@class=&quot;ADXRXN gEQpi5&quot;]/div[@class=&quot;ADXRXN _tKaHB hVtwEZ zEVE_X&quot;]/div[@class=&quot;H2DtUH KwViV7 FE_3R1 KDGhSV Tjcf3c&quot;]/div[@class=&quot;ADXRXN _tKaHB gEQpi5 hVtwEZ zEVE_X&quot;]/div[@class=&quot;ADXRXN XC5OnJ&quot;]/div[@class=&quot;Q3hcOU DodKMr O0u6sV itw4K9 g0I6wi be_g_n ap8aAM&quot;]/div[@class=&quot;ADXRXN g8WGSl h2QNmC&quot;]</value>
      <webElementGuid>788225cb-b866-488d-b183-0283e1f486a5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value></value>
      <webElementGuid>6cc56244-7ae0-4f98-a842-474869a860eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value></value>
      <webElementGuid>59ef7b43-5891-4140-b905-d4197021d1ca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value></value>
      <webElementGuid>133d6c90-b290-4587-801e-4b3caab0ee1c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value></value>
      <webElementGuid>307cafeb-eaa8-4172-8161-4b6cb6ab5e96</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value></value>
      <webElementGuid>93b1cda8-43d8-4820-91fc-0aa19fbae496</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
