<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_MessageContainer</name>
   <tag></tag>
   <elementGuidId>09c64233-6e9f-44e9-b972-670b7a6f4732</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='full-height-inbox-panel']/div/div[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;New messageMessagesNamiiiahNNamiiiah.2mSuggestedhi Ngyn@nanhtrangcp696Anita Mie@&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>baaa8210-3177-48c7-b2ce-e3e2d24b66ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ADXRXN</value>
      <webElementGuid>e2b6caa7-32d9-4376-b587-7d3f0efb90e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>New messageMessagesNamiiiahNNamiiiah.2mSuggestedhi Ngyn@nanhtrangcp696Anita Mie@aanita10mieLiebert Johan@fttieuquyhohfixit@mixed_material_shining_star112Invite your friendsConnect to start chatting</value>
      <webElementGuid>2c1b221c-35da-4da6-a1d4-43913c5745c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;full-height-inbox-panel&quot;)/div[@class=&quot;ADXRXN&quot;]/div[@class=&quot;ADXRXN&quot;]</value>
      <webElementGuid>47668be0-8ccf-4e95-bfc9-f05974b4f76a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='full-height-inbox-panel']/div/div[2]</value>
      <webElementGuid>5ceb0fd7-aae6-45c1-baca-cc8a6010b39f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Messages'])[1]/following::div[4]</value>
      <webElementGuid>cc073d7e-cae2-43f3-8d7e-65ddfa15356a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Martin'])[1]/following::div[54]</value>
      <webElementGuid>7f525e35-a410-4815-801d-eaca2e120e5e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/div/div/div/div[2]</value>
      <webElementGuid>e7628b31-8a6f-4b6f-830c-5f207e38d5a2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'New messageMessagesNamiiiahNNamiiiah.2mSuggestedhi Ngyn@nanhtrangcp696Anita Mie@aanita10mieLiebert Johan@fttieuquyhohfixit@mixed_material_shining_star112Invite your friendsConnect to start chatting' or . = 'New messageMessagesNamiiiahNNamiiiah.2mSuggestedhi Ngyn@nanhtrangcp696Anita Mie@aanita10mieLiebert Johan@fttieuquyhohfixit@mixed_material_shining_star112Invite your friendsConnect to start chatting')]</value>
      <webElementGuid>dec7c8d9-0449-4603-901e-710c6d8f5d40</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
