<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_receive</name>
   <tag></tag>
   <elementGuidId>aaaee328-7965-4ea9-b99f-fcde9e848516</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='full-height-inbox-panel']/div[2]/div/div/div/div/div[12]/div/div[2]/div[2]/div/div/div/div/div/div/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.ADXRXN._tKaHB.gEQpi5.hVtwEZ.zEVE_X > div.ADXRXN.XC5OnJ > div.Q3hcOU.DodKMr.O0u6sV.itw4K9.g0I6wi.be_g_n.ap8aAM</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;.&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>a7f3a08b-9d99-44db-9a11-fe414303556e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>83040695-34b8-4db8-90b1-151382d1b159</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>Q3hcOU DodKMr O0u6sV itw4K9 g0I6wi be_g_n ap8aAM</value>
      <webElementGuid>4ae6757c-76df-430f-bec1-7ad61aa976f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>9017d7f5-463a-469e-ac4f-06a45fa21b49</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>7656d3ab-5188-42e9-aa6a-1f943a79b7e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>.</value>
      <webElementGuid>6746c3e5-3838-4026-9613-5cbcb8519e56</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;full-height-inbox-panel&quot;)/div[@class=&quot;ADXRXN gEQpi5 gSktR2 i1hWBD&quot;]/div[@class=&quot;H2DtUH KwViV7 FE_3R1 _tKaHB qtP9fl xdjfP5&quot;]/div[@class=&quot;ADXRXN _tKaHB drGcEU zEVE_X&quot;]/div[1]/div[@class=&quot;ADXRXN _tKaHB xdjfP5 zEVE_X&quot;]/div[@class=&quot;ADXRXN C6J6UC gEQpi5 zEVE_X&quot;]/div[@class=&quot;ADXRXN TyRBan _tKaHB gbTsx5 hVtwEZ zEVE_X&quot;]/div[@class=&quot;H2DtUH KwViV7 FE_3R1 KDGhSV Tjcf3c i4_mIm&quot;]/div[@class=&quot;H2DtUH KwViV7 FE_3R1 KDGhSV Tjcf3c qtP9fl wl0pCr&quot;]/div[@class=&quot;ADXRXN&quot;]/div[@class=&quot;ADXRXN gEQpi5&quot;]/div[@class=&quot;ADXRXN _tKaHB hVtwEZ zEVE_X&quot;]/div[@class=&quot;H2DtUH KwViV7 FE_3R1 KDGhSV Tjcf3c&quot;]/div[@class=&quot;ADXRXN _tKaHB gEQpi5 hVtwEZ zEVE_X&quot;]/div[@class=&quot;ADXRXN XC5OnJ&quot;]/div[@class=&quot;Q3hcOU DodKMr O0u6sV itw4K9 g0I6wi be_g_n ap8aAM&quot;]</value>
      <webElementGuid>1ba2d5d1-be44-486c-b9e8-8620f101c349</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='full-height-inbox-panel']/div[2]/div/div/div/div/div[12]/div/div[2]/div[2]/div/div/div/div/div/div/div</value>
      <webElementGuid>71d2d240-ddea-4dab-9dad-a37068565b81</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='N'])[3]/following::div[8]</value>
      <webElementGuid>40b1cffa-9d3d-4073-a135-6ef33cd8eccc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Namiiiah'])[5]/following::div[14]</value>
      <webElementGuid>d1b760b8-a3aa-4256-90a9-67f25cb4e6ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/div/div/div/div/div/div</value>
      <webElementGuid>37372054-53b6-4583-a700-0949ba006bf7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = '.' or . = '.')]</value>
      <webElementGuid>010229ba-ad76-47d7-b91b-e9f5abf4ca02</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
