<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Send a Pin</name>
   <tag></tag>
   <elementGuidId>3ba832c8-35e7-4296-b0b6-ae274ec4cc34</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='full-height-inbox-panel']/div[3]/div/div/div/div/div/div[2]/div/div/div/div/div/div/div/div/div/div/div/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.e2jAjp.dHA5K0.N9tO7e > div.ADXRXN.gEQpi5 > img.iFOUS5</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Send Pin to conversation: a close up of a cat wearing a motorcycle helmet with its mouth open and tongue out&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>db955d67-e71d-445e-95dc-9c5ae8b2d5e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>iFOUS5</value>
      <webElementGuid>c63e5e15-a39b-4909-8334-86a0030018e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>draggable</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>58597cb9-b2bd-41db-9491-e59e8140888a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>fetchpriority</name>
      <type>Main</type>
      <value>auto</value>
      <webElementGuid>c0d1a562-df38-47f4-845d-287aaf4f4e31</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>loading</name>
      <type>Main</type>
      <value>auto</value>
      <webElementGuid>d8f61814-b2d3-49e9-bf3c-977bfa30b399</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://i.pinimg.com/474x/67/c5/d5/67c5d5678460c7a30a1b109174b127e4.jpg</value>
      <webElementGuid>c1d50108-70b6-4cf2-8348-4a2b6bc7e537</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;full-height-inbox-panel&quot;)/div[@class=&quot;ADXRXN NYgy1O TfR6nu&quot;]/div[@class=&quot;ADXRXN&quot;]/div[@class=&quot;KvKvqR&quot;]/div[@class=&quot;ADXRXN&quot;]/div[@class=&quot;ADXRXN NYgy1O TfR6nu ecEhnF gcIrSY&quot;]/div[@class=&quot;H2DtUH KwViV7 FE_3R1 KDGhSV _tKaHB qtP9fl&quot;]/div[@class=&quot;ADXRXN gSktR2 hB_pJA wl0pCr&quot;]/div[@class=&quot;ADXRXN&quot;]/div[1]/div[@class=&quot;KnPdox gEQpi5&quot;]/div[@class=&quot;V3gVHw TfR6nu v65fHc&quot;]/div[1]/div[@class=&quot;ADXRXN ekBBbl&quot;]/div[@class=&quot;Q3hcOU dHA5K0 O0u6sV itw4K9 g0I6wi be_g_n ap8aAM&quot;]/div[@class=&quot;ADXRXN gEQpi5&quot;]/div[@class=&quot;ADXRXN ekBBbl&quot;]/div[@class=&quot;e2jAjp dHA5K0 N9tO7e&quot;]/div[@class=&quot;ADXRXN gEQpi5&quot;]/img[@class=&quot;iFOUS5&quot;]</value>
      <webElementGuid>655c865c-5a51-410a-bdbc-1038434b5a0b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='full-height-inbox-panel']/div[3]/div/div/div/div/div/div[2]/div/div/div/div/div/div/div/div/div/div/div/img</value>
      <webElementGuid>3914c435-2e26-4b07-b944-f14981c06b9d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt=' ']</value>
      <webElementGuid>5fe38a69-2f71-4fae-84de-fcdfb1c91870</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/div/div/div/div/div/div/div/img</value>
      <webElementGuid>ce7c65f6-b736-4fe6-ba9c-6f7b97700fdb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://i.pinimg.com/474x/67/c5/d5/67c5d5678460c7a30a1b109174b127e4.jpg']</value>
      <webElementGuid>b47cae27-e818-418f-b4b1-062a336c14ab</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
