<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_searchPrivacySwitch</name>
   <tag></tag>
   <elementGuidId>7fe46351-3cf3-44ba-8dc3-f03c7df10a3c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#searchPrivacySwitch</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='searchPrivacySwitch']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Search privacy&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>3018fc93-c5ac-4b92-aa37-99bb62125bb5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>b4JET0 vwgzs2</value>
      <webElementGuid>2cf70df8-360a-4f6e-921d-548c3f0e874b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>searchPrivacySwitch</value>
      <webElementGuid>46ad6320-3c16-4b66-a742-955db6503158</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>65bccf27-3311-4601-a617-d63df7e78780</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;searchPrivacySwitch&quot;)</value>
      <webElementGuid>41740b05-c533-4aa3-b8c9-0b50db954251</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='searchPrivacySwitch']</value>
      <webElementGuid>1081729c-875b-41d7-ae54-9995e9d8e8d2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__PWS_ROOT__']/div/div/div[3]/div/div/div/div[2]/div/div[2]/form/div/div[2]/div/div/div/div[2]/div/input</value>
      <webElementGuid>c20dfc58-632f-449d-86ab-daf96e8dd03b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div[2]/div/input</value>
      <webElementGuid>7fd2761b-535f-42e6-ac01-6f9268cf291f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'searchPrivacySwitch' and @type = 'checkbox']</value>
      <webElementGuid>d8846feb-1ab4-4a1b-8a22-a278983bd07f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
