<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_privateProfileSwitch</name>
   <tag></tag>
   <elementGuidId>dc4467dd-b899-4fb8-b6a4-1d2c460f1951</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#privateProfileSwitch</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='privateProfileSwitch']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Private profile&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>0450498e-1eb9-4797-bb6b-b1cea2fbf9ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>b4JET0 vwgzs2</value>
      <webElementGuid>d0161fe2-4f3a-4128-a77e-f6db95ce6d2a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>privateProfileSwitch</value>
      <webElementGuid>5c41c499-a05d-47b0-8569-8118281cf792</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>71f4c879-504e-48ff-99e0-dbf2baf07d75</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;privateProfileSwitch&quot;)</value>
      <webElementGuid>4b4db04e-615b-4d97-bf93-7625c66237bd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='privateProfileSwitch']</value>
      <webElementGuid>bf01846f-596e-4694-b156-8be6982928c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__PWS_ROOT__']/div/div/div[3]/div/div/div/div[2]/div/div[2]/form/div/div/div/div/div/div[2]/div/input</value>
      <webElementGuid>f79ad3fa-7f66-47c2-98cd-b9557187d91a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/input</value>
      <webElementGuid>a8c8bcbe-6e81-4d7d-a5ae-892a6443f3b5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'privateProfileSwitch' and @type = 'checkbox']</value>
      <webElementGuid>d2195b86-cec6-4acf-8b07-60f68af854d1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
