<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Follow</name>
   <tag></tag>
   <elementGuidId>21c9dc15-3c75-43e2-9022-d5f0b202e5eb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.G0yGFD.ap8aAM.Q3hcOU.gwpqhu.E6J5D_.GaMK1V.O0u6sV</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@data-test-id='board-follow-button']//button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>[data-test-id=&quot;board-follow-button&quot;] >> internal:label=&quot;Follow&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>828491cf-1c5f-430b-95a5-c2727ca46323</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Follow</value>
      <webElementGuid>a0258711-6395-45b6-af3a-b84e9eed5e43</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>G0yGFD ap8aAM Q3hcOU gwpqhu E6J5D_ GaMK1V O0u6sV</value>
      <webElementGuid>aa4b5bc1-4231-45c2-9141-83eeee484888</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>91c27723-04c2-430d-b3d4-3538e3bf0bcc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>4817f6e8-4fec-470d-a051-a6474fd4c92e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Follow</value>
      <webElementGuid>74da063b-a9cc-4404-ac8d-36f384af223a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;en&quot;]/body[1]/div[@class=&quot;unzjra&quot;]/div[1]/div[1]/div[@class=&quot;asf_Xx&quot;]/div[@class=&quot;YLPkP_ j3H91d c0G7To&quot;]/div[@class=&quot;ADXRXN _tKaHB gEQpi5 wl0pCr zEVE_X&quot;]/div[@class=&quot;ADXRXN MJ_eMy drGcEU gHrR3r wl0pCr&quot;]/div[@class=&quot;ADXRXN drGcEU&quot;]/div[@class=&quot;ADXRXN&quot;]/div[@class=&quot;ADXRXN i1hWBD&quot;]/div[@class=&quot;H2DtUH KwViV7 FE_3R1 Tjcf3c kF2VEF&quot;]/div[@class=&quot;oRZ5_s&quot;]/div[1]/div[@class=&quot;KnPdox gEQpi5&quot;]/div[@class=&quot;V3gVHw TfR6nu v65fHc&quot;]/div[1]/div[@class=&quot;ADXRXN gEQpi5 gSktR2 kF2VEF zEVE_X&quot;]/div[@class=&quot;H2DtUH KwViV7 FE_3R1 KDGhSV Tjcf3c sSBu24&quot;]/div[@class=&quot;ADXRXN B3GZzn TfR6nu mJ2PyB zEVE_X&quot;]/div[@class=&quot;ADXRXN&quot;]/button[@class=&quot;G0yGFD ap8aAM Q3hcOU gwpqhu E6J5D_ GaMK1V O0u6sV&quot;]</value>
      <webElementGuid>0aa5ca11-d84e-4233-b87b-841077af804e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value></value>
      <webElementGuid>f8d6ea6b-8038-4328-8105-de113b1f3321</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value></value>
      <webElementGuid>73215462-6e3d-4940-bdaa-48a86b4badbe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value></value>
      <webElementGuid>41501077-d19e-4f2b-b04a-c6af9cc3ba5e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value></value>
      <webElementGuid>07e7dea0-1978-4fa3-8221-e0b88448e10e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value></value>
      <webElementGuid>608e183f-aa7d-4601-bfa4-a93905b7b63a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value></value>
      <webElementGuid>b8a8be45-647f-43dd-99f8-47e34c046e08</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
