<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_FollowingContainer</name>
   <tag></tag>
   <elementGuidId>496e7b4b-4bde-453c-94a7-95b072193246</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.ADXRXN.MJ_eMy.drGcEU.gEQpi5.gHrR3r.wl0pCr</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@data-test-id='profile-following']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Following&quot;i >> div >> internal:has-text=&quot;Anita MieUnfollowfixitUnfollowValentine | Beauty TipsUnfollowErinUnfollowpatooti&quot;i >> nth=2</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>6a12f0ba-47dd-4e88-a0d9-6aaac7c470e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ADXRXN MJ_eMy drGcEU gEQpi5 gHrR3r wl0pCr</value>
      <webElementGuid>14e937b5-d959-4ca9-9013-0ad2e59f3437</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Anita MieUnfollowfixitUnfollowValentine | Beauty TipsUnfollowErinUnfollowpatooti3UnfollowCherrycosmos ✨UnfollowUser profile pictureAStevensonUnfollow𝒮.Unfollow庭庭Unfollow BuzzFeed Unfollow Cheezburger Unfollow 9GAG Unfollow Wattpad Unfollow</value>
      <webElementGuid>ec73d649-0895-41b6-8913-7a90ef49943a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;en&quot;]/body[1]/div[@class=&quot;unzjra&quot;]/div[1]/div[1]/div[@class=&quot;asf_Xx&quot;]/div[@class=&quot;YLPkP_ j3H91d c0G7To&quot;]/div[@class=&quot;ADXRXN _tKaHB gEQpi5 wl0pCr zEVE_X&quot;]/div[@class=&quot;ADXRXN MJ_eMy drGcEU gEQpi5 gHrR3r wl0pCr&quot;]</value>
      <webElementGuid>52176ed8-c26d-45dc-a21d-f1d05195a913</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value></value>
      <webElementGuid>a463578a-0f55-42c7-90bf-0aef16ec4cb4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value></value>
      <webElementGuid>4cf4b2cc-ea46-4fde-a2d1-e6b3797527bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value></value>
      <webElementGuid>fb592d0b-9d65-4b7c-96a4-600cde647d44</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value></value>
      <webElementGuid>60eff237-802c-4758-9eb2-84a3dc9042e6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
