<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Profile</name>
   <tag></tag>
   <elementGuidId>eacfbd6a-4525-4251-8104-dd6c35c359cd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.ADXRXN.gcIrSY</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='HeaderContent']/div/div/div[2]/div/div/div/div[2]/div/div/div/a/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Your profile&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>11c20ae4-ac8f-4fb6-bea2-db6f43d543d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>6c6b2dc6-3ba5-4b9d-812b-4c7e137f3b01</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ADXRXN gcIrSY</value>
      <webElementGuid>47884a0c-57eb-488c-bec7-bea7fc6e1d85</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;HeaderContent&quot;)/div[@class=&quot;ADXRXN&quot;]/div[@class=&quot;ADXRXN c49R7p g0I6wi ecEhnF&quot;]/div[@class=&quot;ADXRXN&quot;]/div[@class=&quot;H2DtUH KwViV7 FE_3R1 KDGhSV _tKaHB&quot;]/div[@class=&quot;ADXRXN BVzdUh c49R7p g0I6wi sSBu24 wl0pCr zEVE_X&quot;]/div[@class=&quot;ADXRXN c49R7p g0I6wi sSBu24 zEVE_X&quot;]/div[@class=&quot;oRZ5_s&quot;]/div[@class=&quot;ADXRXN&quot;]/div[@class=&quot;ADXRXN DTsIgD&quot;]/div[@class=&quot;ADXRXN&quot;]/a[@class=&quot;etmDmh i7jpet zlD4hU Q3hcOU gcIrSY O0u6sV KQwCbH itw4K9 g0I6wi be_g_n ap8aAM&quot;]/div[@class=&quot;ADXRXN gcIrSY&quot;]</value>
      <webElementGuid>a32b335f-dd0d-423e-abfb-01db5ee7c944</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='HeaderContent']/div/div/div[2]/div/div/div/div[2]/div/div/div/a/div</value>
      <webElementGuid>c568a0af-d351-4bdc-830e-e701f52b456e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Skip to content'])[1]/following::div[20]</value>
      <webElementGuid>f3fdb984-e171-410e-b5ec-6260c5e5e8c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Home'])[1]/preceding::div[75]</value>
      <webElementGuid>06b3319d-6d83-4acb-bebc-f9cf038cff3a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='All'])[1]/preceding::div[76]</value>
      <webElementGuid>dd6ecc8a-19bf-4770-ac74-0e82700c4d10</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/a/div</value>
      <webElementGuid>0e251ecf-2418-4b86-9394-c3ff530ea8c8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
