<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Followers</name>
   <tag></tag>
   <elementGuidId>87c4d5c3-2059-4dcc-9275-a96ec2a825a2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.WuRgKB.aMgNKE.rjBCWf.v_eFe4.qnEc35.eLtWQB.B3NXeR.N6RR6H</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@data-test-id='profile-followers-count']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;2 followers&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>43e49210-4896-46b4-8911-8dee3bd09bdb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>WuRgKB aMgNKE rjBCWf v_eFe4 qnEc35 eLtWQB B3NXeR N6RR6H</value>
      <webElementGuid>09f52f4b-888c-42d0-94b5-643fbfc481db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>2 followers</value>
      <webElementGuid>4dc325f2-4c90-497d-b450-53550e521b60</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__PWS_ROOT__&quot;)/div[@class=&quot;ADXRXN&quot;]/div[@class=&quot;ADXRXN&quot;]/div[@class=&quot;appContent&quot;]/div[@class=&quot;ADXRXN&quot;]/div[@class=&quot;mainContainer&quot;]/div[@class=&quot;ADXRXN&quot;]/div[@class=&quot;ADXRXN&quot;]/div[@class=&quot;KvKvqR&quot;]/div[@class=&quot;ADXRXN ecEhnF&quot;]/div[@class=&quot;ADXRXN MEP_vB OrJwfv aNs6gM qJUqe1 rT2FEs sSBu24 zEVE_X&quot;]/div[@class=&quot;H2DtUH KwViV7 FE_3R1 Tjcf3c qJUqe1&quot;]/div[@class=&quot;ADXRXN DwbjAm Yh17xG _yHzFs dSlwuX&quot;]/a[@class=&quot;etmDmh i7jpet zlD4hU Q3hcOU g8WGSl O0u6sV KQwCbH itw4K9 g0I6wi be_g_n ap8aAM&quot;]/div[@class=&quot;ADXRXN BVzdUh _xSIdT g8WGSl kF2VEF sSBu24 zEVE_X&quot;]/div[@class=&quot;ADXRXN _tKaHB eonSQk l36nOf oubjoF&quot;]/div[@class=&quot;ADXRXN wl0pCr&quot;]/div[@class=&quot;H2DtUH KwViV7 FE_3R1 KDGhSV Tjcf3c sSBu24&quot;]/div[@class=&quot;ADXRXN nnftW_&quot;]/div[@class=&quot;Q3hcOU DodKMr O0u6sV itw4K9 g0I6wi be_g_n ap8aAM&quot;]/span[@class=&quot;WuRgKB aMgNKE rjBCWf v_eFe4 qnEc35 eLtWQB B3NXeR N6RR6H&quot;]</value>
      <webElementGuid>b81c2823-5dbb-4e14-8344-f8267b3a2f39</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value></value>
      <webElementGuid>82a3da8c-c303-4902-a1fb-8cb7875bf8f8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value></value>
      <webElementGuid>63488498-662e-4389-ac6b-982513e13fc5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value></value>
      <webElementGuid>ebe0d03f-9df0-4afd-8911-e332fd5a67be</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value></value>
      <webElementGuid>97dc950b-c733-4ef7-813f-3f58af723211</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value></value>
      <webElementGuid>fa2d0c48-07c8-4963-b362-9bd3ffbd390f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value></value>
      <webElementGuid>2b9c90f6-0388-4b66-ac51-a2be392ff332</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value></value>
      <webElementGuid>81da0270-3a5e-4ef6-8b52-3a933fdf1e36</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value></value>
      <webElementGuid>8f01b70f-87e4-4814-abd8-b5f612ce5b2a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
