<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Following</name>
   <tag></tag>
   <elementGuidId>ea9b69cd-aa2f-49b2-aac9-48f99185b98d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@data-test-id='profile-following-count']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;13 following&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>79b7d407-2857-4f56-8b02-07789005a30d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>WuRgKB aMgNKE rjBCWf v_eFe4 qnEc35 eLtWQB B3NXeR N6RR6H</value>
      <webElementGuid>522c38f1-e37a-4615-904b-a7fb86cc7e6b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>13 following</value>
      <webElementGuid>b83ea721-5392-4e7b-a585-0b1613ae3561</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__PWS_ROOT__&quot;)/div[@class=&quot;ADXRXN&quot;]/div[@class=&quot;ADXRXN&quot;]/div[@class=&quot;appContent&quot;]/div[@class=&quot;ADXRXN&quot;]/div[@class=&quot;mainContainer&quot;]/div[@class=&quot;ADXRXN&quot;]/div[@class=&quot;ADXRXN&quot;]/div[@class=&quot;KvKvqR&quot;]/div[@class=&quot;ADXRXN ecEhnF&quot;]/div[@class=&quot;ADXRXN MEP_vB OrJwfv aNs6gM qJUqe1 rT2FEs sSBu24 zEVE_X&quot;]/div[@class=&quot;H2DtUH KwViV7 FE_3R1 Tjcf3c qJUqe1&quot;]/div[@class=&quot;ADXRXN DwbjAm Yh17xG _yHzFs dSlwuX&quot;]/a[@class=&quot;etmDmh i7jpet zlD4hU Q3hcOU g8WGSl O0u6sV KQwCbH itw4K9 g0I6wi be_g_n ap8aAM&quot;]/div[@class=&quot;ADXRXN BVzdUh _xSIdT g8WGSl kF2VEF sSBu24 zEVE_X&quot;]/div[@class=&quot;ADXRXN _tKaHB eonSQk l36nOf oubjoF&quot;]/div[@class=&quot;ADXRXN wl0pCr&quot;]/div[@class=&quot;H2DtUH KwViV7 FE_3R1 KDGhSV Tjcf3c sSBu24&quot;]/div[@class=&quot;ADXRXN nnftW_&quot;]/div[@class=&quot;Q3hcOU DodKMr O0u6sV itw4K9 g0I6wi be_g_n ap8aAM&quot;]/span[@class=&quot;WuRgKB aMgNKE rjBCWf v_eFe4 qnEc35 eLtWQB B3NXeR N6RR6H&quot;]</value>
      <webElementGuid>06b2ed21-0403-46c3-a96c-ba25120386b9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value></value>
      <webElementGuid>70a9f4e4-37e8-4643-b74c-5b105d6df4ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value></value>
      <webElementGuid>e9fb4cbf-6820-49dc-b131-f5761bfc33ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value></value>
      <webElementGuid>cbe13338-6da0-4893-803e-c9a1ea14629b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value></value>
      <webElementGuid>c5ed517b-22a8-4915-ad8d-825327ead0ca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value></value>
      <webElementGuid>462f4a30-4236-4614-895f-d6349b345a6b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value></value>
      <webElementGuid>6f54c2e1-d37a-4c78-9a15-9bea2fb86aee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value></value>
      <webElementGuid>418ac039-c54c-4b5f-b8cb-8166e840c555</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value></value>
      <webElementGuid>cc410a9a-e326-4e92-a389-f4a494bf43c7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
