<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Delete</name>
   <tag></tag>
   <elementGuidId>3d4e3e8f-692c-45bb-8718-320521de8833</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.G0yGFD.ap8aAM.Q3hcOU.gwpqhu.itmoZr.CNPSpi.O0u6sV</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@data-test-id='confirm-button']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>[data-test-id=&quot;confirm-button&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>9cfb1768-7c45-4886-82c1-026f958bf1b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Confirm delete board</value>
      <webElementGuid>de50cacb-e89c-449c-84d8-26895c60c5aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>G0yGFD ap8aAM Q3hcOU gwpqhu itmoZr CNPSpi O0u6sV</value>
      <webElementGuid>9dee18b5-5bf4-4b09-abcb-bfafbd04fd21</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-test-id</name>
      <type>Main</type>
      <value>confirm-button</value>
      <webElementGuid>5b1ebf22-e432-4e51-90ae-de45fe81d13f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>fe3d02c6-508c-409a-8204-a306c44fbff6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>ca8b67d5-8e44-44c0-922b-3ca8b65231aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Delete</value>
      <webElementGuid>62123cf6-13d1-4299-b71e-18ad9385745e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;en&quot;]/body[1]/div[@class=&quot;unzjra&quot;]/div[1]/div[@class=&quot;asf_Xx&quot;]/div[@class=&quot;YLPkP_ j3H91d c0G7To&quot;]/div[@class=&quot;ADXRXN _tKaHB gEQpi5 wl0pCr zEVE_X&quot;]/div[@class=&quot;ADXRXN dDmW3o gEQpi5&quot;]/div[@class=&quot;ADXRXN CQ1_jt b6DHg3&quot;]/div[@class=&quot;H2DtUH KwViV7 FE_3R1 Tjcf3c xdjfP5&quot;]/div[@class=&quot;H2DtUH opw_4g H__hJz Tjcf3c rT2FEs&quot;]/div[@class=&quot;oRZ5_s&quot;]/button[@class=&quot;G0yGFD ap8aAM Q3hcOU gwpqhu itmoZr CNPSpi O0u6sV&quot;]</value>
      <webElementGuid>7dcfb3e5-25d2-4069-98ad-944de048a4a9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value></value>
      <webElementGuid>5b76fd4f-2d6a-487a-a945-f579f226a5b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value></value>
      <webElementGuid>0cf263e9-d3ad-4b9f-b6b6-070bc0621213</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value></value>
      <webElementGuid>5217c3d9-1456-40cc-9334-4caf427a281b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value></value>
      <webElementGuid>d400e3e6-3b10-4131-a360-0b5ad9755bb0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value></value>
      <webElementGuid>199d51a5-b565-4817-9c9d-0358dc9d2c49</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
