<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Delete board</name>
   <tag></tag>
   <elementGuidId>50607758-e8f7-4294-8039-8947383adb53</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>h4.wyEmcc.qnEc35.WuRgKB.u04llW.yv4JQN.iuUxZ9</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@data-test-id='deleteBoardButton']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Delete board You have 7 days to restore a deleted Board. After that, it will be permanently deleted.&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h4</value>
      <webElementGuid>75f256ac-14c2-4a08-b11c-1689b40d7e9f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>wyEmcc qnEc35 WuRgKB u04llW yv4JQN iuUxZ9</value>
      <webElementGuid>22468409-4ce1-452e-a586-15a7f5932d17</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Delete board</value>
      <webElementGuid>b76253af-5b85-4076-b745-ab4d8f0011da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;en&quot;]/body[1]/div[@class=&quot;unzjra&quot;]/div[1]/div[1]/div[@class=&quot;asf_Xx&quot;]/div[@class=&quot;YLPkP_ j3H91d c0G7To&quot;]/div[@class=&quot;ADXRXN _tKaHB gEQpi5 wl0pCr zEVE_X&quot;]/div[@class=&quot;ADXRXN MJ_eMy drGcEU gEQpi5 gHrR3r wl0pCr&quot;]/div[@class=&quot;ADXRXN MEP_vB aNs6gM dHA5K0&quot;]/form[1]/div[@class=&quot;ADXRXN AsRsEE&quot;]/div[@class=&quot;ADXRXN ekBBbl&quot;]/div[@class=&quot;ADXRXN _xSIdT ub_cVk&quot;]/div[@class=&quot;Q3hcOU DodKMr O0u6sV itw4K9 g0I6wi be_g_n ap8aAM&quot;]/div[@class=&quot;ADXRXN eOQXgz ekBBbl&quot;]/h4[@class=&quot;wyEmcc qnEc35 WuRgKB u04llW yv4JQN iuUxZ9&quot;]</value>
      <webElementGuid>15ad1b35-1728-42b7-8dbc-894c7607cce8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value></value>
      <webElementGuid>7ffe7082-7a48-4516-8cf7-6cf6f0140438</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value></value>
      <webElementGuid>b75eda25-39ed-4a15-9cd9-ac65aab227a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value></value>
      <webElementGuid>7ab55eec-b28b-462a-82a0-8b5434d9e0b5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value></value>
      <webElementGuid>045fca39-6dc2-4a9e-82f5-b08d67d7c607</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value></value>
      <webElementGuid>34afc221-183e-4f5e-b467-5102b3fe3430</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value></value>
      <webElementGuid>aeb3cdbf-1396-4ac0-bfcd-d1b02bf7cc34</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
