<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Edit_Board</name>
   <tag></tag>
   <elementGuidId>9ddafa1f-b737-4bf2-9383-eada6c318b28</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.ADXRXN.OrJwfv.g8WGSl.kF2VEF.xLeAAe.zEVE_X</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@data-test-id='more-board-options']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;more options&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>a1c0cabc-9bfd-46f6-b3f6-757412b06df6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ADXRXN OrJwfv g8WGSl kF2VEF xLeAAe zEVE_X</value>
      <webElementGuid>7ef5abc7-508b-4ead-b351-97616594869f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__PWS_ROOT__&quot;)/div[@class=&quot;ADXRXN&quot;]/div[@class=&quot;ADXRXN&quot;]/div[@class=&quot;appContent&quot;]/div[@class=&quot;ADXRXN&quot;]/div[@class=&quot;mainContainer&quot;]/div[@class=&quot;ADXRXN&quot;]/div[@class=&quot;ADXRXN&quot;]/div[@class=&quot;ADXRXN gSktR2&quot;]/div[@class=&quot;ADXRXN _tKaHB djbjbM zEVE_X&quot;]/div[@class=&quot;ADXRXN LbyOQL gSktR2&quot;]/div[@class=&quot;boardFeedAlignmentWrapper&quot;]/div[@class=&quot;H2DtUH KwViV7 FE_3R1 Tjcf3c hVtwEZ qJUqe1&quot;]/div[@class=&quot;ADXRXN&quot;]/div[@class=&quot;H2DtUH c1Gamg z6WAHi Tjcf3c&quot;]/div[@class=&quot;oRZ5_s&quot;]/div[@class=&quot;ADXRXN M9Ye1t&quot;]/div[@class=&quot;ADXRXN gEQpi5&quot;]/div[@class=&quot;ADXRXN&quot;]/div[@class=&quot;Q3hcOU g8WGSl O0u6sV itw4K9 g0I6wi be_g_n ap8aAM&quot;]/div[@class=&quot;ADXRXN OrJwfv g8WGSl kF2VEF xLeAAe zEVE_X&quot;]</value>
      <webElementGuid>4cfa722f-9e8f-444a-81f6-0180be56e860</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value></value>
      <webElementGuid>588e7d9a-35da-4ebd-9ec7-3a7bae7ff201</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value></value>
      <webElementGuid>6808dcd0-a44e-49da-89a5-f28900f9fc44</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value></value>
      <webElementGuid>faf652f9-6cfe-4f46-a64c-168836ac3d6b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value></value>
      <webElementGuid>7006d88f-afb8-453a-ba58-cf6cd050dc35</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value></value>
      <webElementGuid>181fc029-aedc-47da-9b73-7dbf2fc6c52b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
