<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Bt_EditBoard</name>
   <tag></tag>
   <elementGuidId>0f0b4c0c-0326-4438-b8e4-5b2c4bfe810a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.ADXRXN.OrJwfv.g8WGSl.kF2VEF.xLeAAe.zEVE_X</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@data-test-id='more-board-options']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>0f476976-b98e-40e0-99fa-94bb8a57653b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ADXRXN OrJwfv g8WGSl kF2VEF xLeAAe zEVE_X</value>
      <webElementGuid>4420babe-fd41-4986-a747-9af10111ca53</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__PWS_ROOT__&quot;)/div[@class=&quot;ADXRXN&quot;]/div[@class=&quot;ADXRXN&quot;]/div[@class=&quot;appContent&quot;]/div[@class=&quot;ADXRXN&quot;]/div[@class=&quot;mainContainer&quot;]/div[@class=&quot;ADXRXN&quot;]/div[@class=&quot;ADXRXN&quot;]/div[@class=&quot;ADXRXN gSktR2&quot;]/div[@class=&quot;ADXRXN _tKaHB djbjbM zEVE_X&quot;]/div[@class=&quot;ADXRXN LbyOQL gSktR2&quot;]/div[@class=&quot;boardFeedAlignmentWrapper&quot;]/div[@class=&quot;H2DtUH KwViV7 FE_3R1 Tjcf3c hVtwEZ qJUqe1&quot;]/div[@class=&quot;ADXRXN&quot;]/div[@class=&quot;H2DtUH c1Gamg z6WAHi Tjcf3c&quot;]/div[@class=&quot;oRZ5_s&quot;]/div[@class=&quot;ADXRXN M9Ye1t&quot;]/div[@class=&quot;ADXRXN gEQpi5&quot;]/div[@class=&quot;ADXRXN&quot;]/div[@class=&quot;Q3hcOU g8WGSl O0u6sV itw4K9 g0I6wi be_g_n ap8aAM&quot;]/div[@class=&quot;ADXRXN OrJwfv g8WGSl kF2VEF xLeAAe zEVE_X&quot;]</value>
      <webElementGuid>80b09026-50e6-4404-8c66-db66fa4361de</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value></value>
      <webElementGuid>a08fd87e-f436-4909-90b1-b838f3f8896b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value></value>
      <webElementGuid>1f680615-6e47-4dfc-b99b-4e07ab2bdf2e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value></value>
      <webElementGuid>dfd6fca4-51eb-47a1-8d60-d596fe0c6986</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value></value>
      <webElementGuid>1a1ac242-1943-4e86-88ec-46e6630ad1ee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value></value>
      <webElementGuid>53580856-1661-4ef0-bcdb-aad194cb7a86</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value></value>
      <webElementGuid>16bc4fb6-820a-4faa-8a3d-68a600c00b16</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
