<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Edit board</name>
   <tag></tag>
   <elementGuidId>014e6250-e5f0-4682-953e-3e0451eb6192</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.ADXRXN.B3GZzn._tKaHB.dHA5K0.i1hWBD.qzrGlv.zEVE_X</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@data-test-id='editBoardButton']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>e7b44f73-23ad-4ca2-aa3f-8319ff7303a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ADXRXN B3GZzn _tKaHB dHA5K0 i1hWBD qzrGlv zEVE_X</value>
      <webElementGuid>0504711d-9278-4ae2-ac69-0afba8e9dcd4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Edit board</value>
      <webElementGuid>73d60d2e-5621-4fef-8fee-3244efc23f64</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;board_options-item-0&quot;)/div[@class=&quot;ADXRXN B3GZzn _tKaHB dHA5K0 i1hWBD qzrGlv zEVE_X&quot;]</value>
      <webElementGuid>c4f16611-5792-4e7b-b431-4199d3f7f7d8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value></value>
      <webElementGuid>bab61b7c-a14c-4e1b-b090-4d0454c40704</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value></value>
      <webElementGuid>ce603465-c107-44d0-84ff-a84482e816cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value></value>
      <webElementGuid>43bf51ac-8c51-49bf-9add-4a64f2bef2c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value></value>
      <webElementGuid>6b4f70fa-272c-412d-8ff2-9830e67cfbd4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value></value>
      <webElementGuid>bdcd3b10-6443-4fa9-99c9-bef9afe05e27</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value></value>
      <webElementGuid>44339974-d53d-4b71-8d71-3a697d3b009c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
