<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_BoardEditName</name>
   <tag></tag>
   <elementGuidId>acb85c38-1758-460c-a183-1fdd24570668</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='boardEditName']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#boardEditName</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Like \&quot;Places to Go\&quot; or \&quot;Recipes to Make\&quot;&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ef6188cd-a12d-422c-bb26-5519e9952596</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>f0c80e8e-a1c4-4ba8-9e87-83e9f4d2ebc3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>VTVmV8 q3kIpX g0zfi1 bb8HPP zNJ6Me c3eeZM vr41LG EYma4O hxKTA7 mm0O_j VpxGtC glzo1E btwCoE</value>
      <webElementGuid>4ac210a8-129d-4675-917d-3ee9b36596a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>boardEditName</value>
      <webElementGuid>4902dfb6-670b-4414-b7ec-4fd11f7286d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Like &quot;Places to Go&quot; or &quot;Recipes to Make&quot;</value>
      <webElementGuid>facd8e83-43af-4653-96dc-9891956d7e13</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>4a3564b0-5f15-4958-affc-59719aa4ab47</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Meow</value>
      <webElementGuid>1c145ed2-84f5-47dd-8027-231cf6e16a83</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>boardName</value>
      <webElementGuid>b9455f19-c8ec-42d3-b79b-a7da6423ad1e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;boardEditName&quot;)</value>
      <webElementGuid>96f766d9-2eda-4d64-b0d4-2445916702d3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='boardEditName']</value>
      <webElementGuid>71bd937a-2860-44c1-9a1e-c527dce2714a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/input</value>
      <webElementGuid>67d335a1-52cd-41b6-9ff6-31c1cb83190a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'boardEditName' and @placeholder = 'Like &quot;Places to Go&quot; or &quot;Recipes to Make&quot;' and @type = 'text' and @name = 'boardName']</value>
      <webElementGuid>c4534c0b-d89e-41f0-81da-bc45276a000f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
