<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Notifications</name>
   <tag></tag>
   <elementGuidId>33852439-c99f-4dbb-8d52-ed28e22cd081</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__PWS_ROOT__']/div/div/div[3]/div/div/div/div[2]/div/div/nav/div[7]/a/div/div/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Notifications&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>57e22dd7-c732-4583-a17b-710f80a19d86</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>WuRgKB aMgNKE YfEt3H v_eFe4 qnEc35 hxKTA7 rszMzv</value>
      <webElementGuid>fabbfbcd-f86e-43bc-ae65-71bd5f981751</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Notifications</value>
      <webElementGuid>fa26aafe-5baf-4c85-a2dc-f198fa45f4bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__PWS_ROOT__&quot;)/div[@class=&quot;ADXRXN&quot;]/div[@class=&quot;ADXRXN&quot;]/div[@class=&quot;appContent&quot;]/div[@class=&quot;ADXRXN&quot;]/div[@class=&quot;mainContainer&quot;]/div[@class=&quot;ADXRXN C48Khy KDGhSV Tjcf3c zEVE_X&quot;]/div[@class=&quot;ADXRXN c49R7p g0I6wi zDq_D0 PSnbKb&quot;]/div[@class=&quot;ADXRXN C48Khy _tKaHB eeaciM gbTsx5 xLeAAe zEVE_X&quot;]/div[@class=&quot;ADXRXN c49R7p g0I6wi xIYl9O GMcNoQ&quot;]/nav[@class=&quot;ADXRXN _tKaHB zEVE_X&quot;]/div[@class=&quot;ADXRXN FqjzhQ WkuYsj dHA5K0&quot;]/a[@class=&quot;etmDmh i7jpet zlD4hU Q3hcOU DodKMr O0u6sV KQwCbH itw4K9 g0I6wi be_g_n ap8aAM&quot;]/div[@class=&quot;ADXRXN Tjcf3c gSktR2 i1hWBD zEVE_X&quot;]/div[@class=&quot;ADXRXN gEQpi5 nnftW_&quot;]/div[@class=&quot;WuRgKB aMgNKE YfEt3H v_eFe4 qnEc35 hxKTA7 rszMzv&quot;]</value>
      <webElementGuid>c2a2cf86-9dc7-4593-82de-32a598dd13f9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__PWS_ROOT__']/div/div/div[3]/div/div/div/div[2]/div/div/nav/div[7]/a/div/div/div</value>
      <webElementGuid>e5435298-f1fc-43cb-8fe5-a64e4c483d85</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Social permissions'])[1]/following::div[5]</value>
      <webElementGuid>48ae6ea8-a882-42f9-8ca5-dd6d951e8cdf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Link to Pinterest'])[1]/following::div[9]</value>
      <webElementGuid>c98742f4-0e6f-40d3-b904-a15591f18194</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Privacy and data'])[1]/preceding::div[1]</value>
      <webElementGuid>364d3da8-d508-4c4a-b996-2cdd1f94310b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Security'])[1]/preceding::div[5]</value>
      <webElementGuid>38de389b-5a33-4eac-8461-365ba2e33798</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Notifications']/parent::*</value>
      <webElementGuid>babebabc-7341-4314-86da-ec1815f9c9d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/a/div/div/div</value>
      <webElementGuid>d679678e-70d0-4461-a052-1a5e143143ca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Notifications' or . = 'Notifications')]</value>
      <webElementGuid>7228ab54-b2ee-4358-a20f-3ac616e13570</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
