<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Security</name>
   <tag></tag>
   <elementGuidId>e6f1ed41-b444-410f-8e92-87b6aa5d7d24</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__PWS_ROOT__']/div/div/div[3]/div/div/div/div[2]/div/div/nav/div[9]/a/div/div/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Security&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>c0aee3e7-aec2-4107-9717-6671902b1c01</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>WuRgKB aMgNKE YfEt3H v_eFe4 qnEc35 hxKTA7 rszMzv</value>
      <webElementGuid>74ec8f0a-9452-42df-a802-d44f4567ee58</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Security</value>
      <webElementGuid>8c384a77-534c-46d5-9136-eb52c2dce961</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__PWS_ROOT__&quot;)/div[@class=&quot;ADXRXN&quot;]/div[@class=&quot;ADXRXN&quot;]/div[@class=&quot;appContent&quot;]/div[@class=&quot;ADXRXN&quot;]/div[@class=&quot;mainContainer&quot;]/div[@class=&quot;ADXRXN C48Khy KDGhSV Tjcf3c zEVE_X&quot;]/div[@class=&quot;ADXRXN c49R7p g0I6wi zDq_D0 PSnbKb&quot;]/div[@class=&quot;ADXRXN C48Khy _tKaHB eeaciM gbTsx5 xLeAAe zEVE_X&quot;]/div[@class=&quot;ADXRXN c49R7p g0I6wi xIYl9O GMcNoQ&quot;]/nav[@class=&quot;ADXRXN _tKaHB zEVE_X&quot;]/div[@class=&quot;ADXRXN FqjzhQ WkuYsj dHA5K0&quot;]/a[@class=&quot;etmDmh i7jpet zlD4hU Q3hcOU DodKMr O0u6sV KQwCbH itw4K9 g0I6wi be_g_n ap8aAM&quot;]/div[@class=&quot;ADXRXN Tjcf3c gSktR2 i1hWBD zEVE_X&quot;]/div[@class=&quot;ADXRXN gEQpi5 nnftW_&quot;]/div[@class=&quot;WuRgKB aMgNKE YfEt3H v_eFe4 qnEc35 hxKTA7 rszMzv&quot;]</value>
      <webElementGuid>e06f3465-9c4d-4f73-b059-61c1cba7ce73</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__PWS_ROOT__']/div/div/div[3]/div/div/div/div[2]/div/div/nav/div[9]/a/div/div/div</value>
      <webElementGuid>91a77ce9-5c10-4367-8588-1d900c6792ca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Privacy and data'])[1]/following::div[4]</value>
      <webElementGuid>583ce78d-ca39-455d-a0d9-040d0ff6bc5a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Notifications'])[1]/following::div[8]</value>
      <webElementGuid>d8c88b57-8732-4a0c-bc95-a0a9805665cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Branded Content'])[1]/preceding::div[1]</value>
      <webElementGuid>47524ac4-5247-4974-9ec3-b5e99d0ad25a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Social permissions'])[2]/preceding::div[5]</value>
      <webElementGuid>b96a5396-573a-4a06-82e5-e6b8ced6679f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Security']/parent::*</value>
      <webElementGuid>18e894a7-5298-453f-9d12-bad7d5367729</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[9]/a/div/div/div</value>
      <webElementGuid>158dcf16-5fd9-4fb3-ae1e-4f69ccf7ea9d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Security' or . = 'Security')]</value>
      <webElementGuid>dfdd8e0e-72db-400f-a3c7-24068e5cd4e7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
