<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea__message</name>
   <tag></tag>
   <elementGuidId>15cca303-c6b5-41c7-943c-c83bdbe46c30</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='messageDraft']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#messageDraft</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Type a message...&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>2ca8a6e8-12d6-4048-8576-b6dd37f2d4bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Type a message to Namiiiah</value>
      <webElementGuid>70fed179-7b32-494c-ac92-55d88c16590d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-gestalt-valid-html</name>
      <type>Main</type>
      <value>TextArea</value>
      <webElementGuid>567f7a93-5f1a-417f-9f2b-58135cbdaa45</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>messageDraft</value>
      <webElementGuid>a7c94644-8648-414e-b385-0f5afdf869b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Type a message...</value>
      <webElementGuid>22f81222-a5ba-4334-8d41-86ab3b9309ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>c75efc6b-2d26-4c7f-8514-dab0b6dced81</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;messageDraft&quot;)</value>
      <webElementGuid>699e65c0-19b1-4fcb-860e-1e6ec5979424</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='messageDraft']</value>
      <webElementGuid>d3cd0dff-5737-4a71-b89d-f91ef5e66213</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='full-height-inbox-panel']/div[3]/div/div/div/div[2]/div/textarea</value>
      <webElementGuid>4f955cd9-fb8e-4e3e-adab-034404a68252</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>c61a37f9-f516-47d5-b80e-9eb82be19421</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = 'messageDraft' and @placeholder = 'Type a message...']</value>
      <webElementGuid>d6f2f80d-4191-4264-a031-b2b2213ea6a5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
